Repository epinio/epinio, pull requests merged in 2021-03, with the labels that each got.

#207 fix: Do not delete Services with bound apps
  acceptance/apps_test.go
  acceptance/bindings_test.go
  acceptance/catalog_services_test.go
  acceptance/custom_services_test.go
  acceptance/features_test.go
  acceptance/orgs_test.go
  acceptance/utilities_test.go
  cmd/internal/client/delete-service.go
  cmd/internal/client/unbind-service.go
  internal/application/application.go
  paas/client.go
  paas/config/config.go
  paas/gitea/resolver.go
Labels: chore, enhancement, ux

#202 fix: replace carrier labels with kubernetes generic ones
  embedded-files/app-ingress.yaml
  paas/client.go
  statik/statik.go
Labels: wip

#209 Fix: Wait for service to be provisioned
  acceptance/catalog_services_test.go
  acceptance/custom_services_test.go
  acceptance/services_test.go
  acceptance/utilities_test.go
  cmd/internal/client/create-service.go
  cmd/internal/client/service.go
  cmd/root.go
  internal/duration/duration.go
  internal/interfaces/interfaces.go
  internal/services/catalog_service.go
  internal/services/custom_service.go
  paas/client.go
Labels: enhancement, goobe, ux

#223 Fix Un/bind service in conflict
  internal/application/application.go
Labels: bug

#232 Added command to show app details
  Makefile
  acceptance/apps_test.go
  acceptance/bindings_test.go
  acceptance/utilities_test.go
  acceptance/wordpress_test.go
  cmd/internal/client/apps.go
  cmd/root.go
  paas/client.go
Labels: enhancement, ux
