Repository epinio/epinio, pull requests merged in 2021-05, with the labels that each got.

#345 Remove gitlint references
  .gitlint
  Makefile
Labels: chore

#351 fix: explicity handle org-namespace already exist case
  acceptance/api_v1_orgs_test.go
  internal/organizations/organizations.go
Labels: bug

#356 Fix upload breakage for push with app directory
  acceptance/apps_test.go
  acceptance/utilities_test.go
  internal/cli/clients/client.go
Labels: bug

#369 feat: show table entries in sorted order
  internal/api/v1/models/sort.go
  internal/application/application.go
  internal/cli/clients/client.go
  internal/services/catalog_service.go
Labels: enhancement, goobe, ux

#390 feat: remove remaining irrelevant client side org checks
  internal/cli/clients/client.go
Labels: chore

#371 368 application scale
  acceptance/acceptance_suite_test.go
  acceptance/api_v1_applications_test.go
  acceptance/api_v1_orgs_test.go
  acceptance/api_v1_services_mutation_test.go
  acceptance/apps_test.go
  acceptance/bindings_test.go
  acceptance/catalog_services_test.go
  acceptance/custom_services_test.go
  acceptance/utilities_test.go
  internal/api/v1/applications.go
  internal/api/v1/models/models.go
  internal/api/v1/router.go
  internal/api/v1/upload.go
  internal/application/application.go
  internal/cli/apps.go
  internal/cli/clients/client.go
  internal/cli/clients/gitea/upload.go
  internal/cli/push.go
Labels: enhancement, ux

#374 feat: internal dev docs/notes about cat configuration elements
  acceptance/acceptance_suite_test.go
  docs/acceptance_tests.md
Labels: documentation

#399 fix: restrict app service to app pods
  internal/cli/clients/gitea/upload.go
Labels: bug

#397 fix: regression for long app names breaking staging
  acceptance/apps_test.go
  internal/api/v1/stage.go
Labels: bug, chore

#398 fix: Add missing template to info controller
  internal/web/info_controller.go
Labels: bug, ux

#405 Generate credentials
  acceptance/acceptance_suite_test.go
  assets/container-registry/chart/container-registry/templates/container-registry.yaml
  assets/container-registry/chart/container-registry/values.yaml
  assets/embedded-files/container-registry-0.1.0.tgz
  deployments/epinio.go
  deployments/gitea.go
  deployments/registry.go
  deployments/tekton.go
  go.mod
  helpers/randstr/randstr.go
  internal/api/v1/stage.go
  internal/auth/auth.go
  internal/cli/clients/client.go
  internal/cli/clients/gitea/gitea.go
  internal/cli/clients/gitea/upload.go
  internal/cli/config/config.go
  internal/cli/install.go
  internal/domain/domain.go
  internal/web/info_controller.go
Labels: goobe, security

#415 feat: use gitea connection credentials for the gitea database as well
  deployments/gitea.go
Labels: goobe, security

#413 chore: auto generate the tarball of the registry chart
  .github/workflows/main.yml
  .gitignore
  Makefile
  assets/embedded-files/container-registry-0.1.0.tgz
Labels: devops admin, enhancement, goobe

#418 feat: remove apparently unused fixed credentials
  deployments/gitea.go
  go.sum
Labels: goobe, security

#414 Updating workload keeps replica count
  acceptance/acceptance_suite_test.go
  acceptance/api_v1_applications_test.go
  acceptance/apps_test.go
  assets/embedded-files/epinio/roles.yaml
  deployments/epinio.go
  internal/api/v1/applications.go
  internal/api/v1/models/models.go
  internal/api/v1/stage.go
  internal/cli/apps.go
  internal/cli/clients/client.go
  internal/cli/push.go
Labels: bug

#427 feat: Documentation around --skip-traefik
  README.md
  docs/advanced.md
Labels: documentation
