Repository epinio/epinio, pull requests merged in 2021-12, with the labels that each got.

#1023 Provide previous app image to tekton for re-use.
  assets/embedded-files/tekton/buildpacks-task.yaml
  assets/embedded-files/tekton/stage-pipeline.yaml
  internal/api/v1/application/stage.go
  internal/application/application.go
  internal/application/workload.go
  pkg/api/core/v1/models/app.go
Labels: enhancement, performance, spike

#1019 CI: add S3 storage tests in EKS
  .github/workflows/eks.yml
  acceptance/install/scenario4_test.go
Labels: QA

#1038 feat: new api endpoint for service updates
  acceptance/api/v1/services_test.go
  acceptance/namespaces_test.go
  acceptance/services_test.go
  docs/references/api/swagger.json
  go.mod
  helm/chart/epinio/templates/server.yaml
  internal/api/v1/docs/service.go
  internal/api/v1/router.go
  internal/api/v1/service/update.go
  internal/application/workload.go
  internal/cli/service.go
  internal/cli/usercmd/service.go
  internal/services/services.go
  pkg/api/core/v1/client/services.go
  pkg/api/core/v1/models/models.go
Labels: enhancement, api, milestone3, dashboard

#1061 CI: bring back acceptance-install tests
  .github/workflows/aks.yml
  .github/workflows/eks.yml
  .github/workflows/gke.yml
  .github/workflows/main.yml
  .github/workflows/rke.yml
  Makefile
  acceptance/helpers/epinio/epinio.go
  acceptance/install/scenario2_test.go
  acceptance/install/scenario3_test.go
  acceptance/install/scenario4_test.go
  acceptance/install/scenario5_test.go
  acceptance/install/suite_test.go
  assets/tests/config-metallb-rke.yml
  assets/tests/values-metallb-rke.yml
  scripts/get-free-ip.sh
  scripts/remove-helm-repos.sh
  scripts/setup-github-action-runner.sh
Labels: QA

#1016 CI: use letsencrypt-staging
  acceptance/install/scenario2_test.go
  acceptance/install/scenario3_test.go
  acceptance/install/scenario4_test.go
  acceptance/install/scenario5_test.go
  assets/tests/letsencrypt-staging.yaml
Labels: QA
