Repository epinio/epinio, pull requests merged in 2021-06, with the labels that each got.

#443 Extended `app logs` to support `--staging`
  acceptance/apps_test.go
  assets/embedded-files/epinio/server.yaml
  internal/api/v1/stage.go
  internal/application/application.go
  internal/cli/apps.go
  internal/cli/clients/client.go
Labels: enhancement

#445 Secure Epinio API ingress with TLS
  README.md
  acceptance/acceptance_suite_test.go
  acceptance/api_v1_applications_test.go
  acceptance/api_v1_orgs_test.go
  acceptance/utilities_test.go
  acceptance/wordpress_test.go
  deployments/epinio.go
  internal/api/v1/stage.go
  internal/auth/certs.go
  internal/cli/clients/epinio_api.go
  internal/cli/clients/install_client.go
  internal/cli/config/config.go
Labels: security

#459 feat: embed the quarks secret chart into the binary
  Makefile
  assets/embedded-files/quarks-secret-1.0.760.tgz
  deployments/quarks.go
Labels: enhancement, quarks

#458 feat: New option `--skip-ssl-verification`
  acceptance/acceptance_suite_test.go
  internal/cli/config/config.go
  internal/cli/root.go
Labels: enhancement, security

#462 fix: Wait for the namespace to be gone
  deployments/service_catalog.go
Labels: bug

#465 Cleanup ingress left behind by app deletion
  acceptance/apps_test.go
  assets/embedded-files/epinio/server.yaml
  internal/application/application.go
Labels: bug

#460 feat: Delete apps in an org parallelly
  internal/api/v1/organizations.go
Labels: safe to test

#472 API Error Handling and Contexts
  acceptance/api_v1_services_mutation_test.go
  acceptance/utilities_test.go
  deployments/cert_manager.go
  deployments/epinio.go
  deployments/gitea.go
  deployments/google_services.go
  deployments/linkerd.go
  deployments/minibroker.go
  deployments/quarks.go
  deployments/registry.go
  deployments/service_catalog.go
  deployments/tekton.go
  deployments/traefik.go
  helpers/kubernetes/cluster.go
  helpers/kubernetes/deployment.go
  helpers/kubernetes/kubernetesfakes/fake_deployment.go
  helpers/kubernetes/platform/generic/generic.go
  helpers/kubernetes/platform/ibm/ibm.go
  helpers/kubernetes/platform/k3s/k3s.go
  helpers/kubernetes/platform/kind/kind.go
  helpers/kubernetes/platform/minikube/minikube.go
  internal/api/v1/applications.go
  internal/api/v1/errors.go
  internal/api/v1/info.go
  internal/api/v1/organizations.go
  internal/api/v1/router.go
  internal/api/v1/servicebindings.go
  internal/api/v1/serviceclasses.go
  internal/api/v1/serviceplans.go
  internal/api/v1/services.go
  internal/api/v1/stage.go
  internal/api/v1/upload.go
  internal/application/application.go
  internal/cli/apps.go
  internal/cli/clients/client.go
  internal/cli/clients/epinio_api.go
  internal/cli/clients/gitea/gitea.go
  internal/cli/clients/install_client.go
  internal/cli/clients/push.go
  internal/cli/delete.go
  internal/cli/disable.go
  internal/cli/enable.go
  internal/cli/info.go
  internal/cli/install.go
  internal/cli/orgs.go
  internal/cli/push.go
  internal/cli/service.go
  internal/cli/target.go
  internal/cli/uninstall.go
  internal/domain/domain.go
  internal/interfaces/interfaces.go
  internal/organizations/organizations.go
  internal/services/catalog_service.go
  internal/services/custom_service.go
  internal/services/services.go
  internal/web/applications_controller.go
  internal/web/info_controller.go
  internal/web/orgs_controller.go
Labels: enhancement

#478 Internal docs explaining the logic of concurrently deleting apps
  internal/api/v1/organizations.go
Labels: documentation

#483 Move unstaging of old runs into the pipeline itself
  assets/embedded-files/tekton/pipeline.yaml
  internal/api/v1/stage.go
Labels: enhancement

#492 Cleanup some small things
  acceptance/utilities_test.go
  deployments/quarks.go
  deployments/tekton.go
  internal/api/v1/applications.go
  internal/api/v1/models/app.go
  internal/application/application.go
Labels: chore

#491 Separate Traefik Installation
  acceptance/acceptance_suite_test.go
  deployments/linkerd.go
  deployments/traefik.go
  internal/cli/clients/install_client.go
  internal/cli/install.go
  internal/cli/root.go
Labels: enhancement

#497 Document Traefik / Linkerd interactions
  docs/advanced.md
Labels: documentation, enhancement

#498 Upgrade to latest release of color package
  go.mod
  go.sum
Labels: bug, ux, windows

#501 Extended management of API certs and credentials in cli config
  acceptance/config_test.go
  acceptance/utilities_test.go
  assets/embedded-files/epinio/server.yaml
  deployments/epinio.go
  docs/configuration.md
  internal/cli/apps.go
  internal/cli/clients/client.go
  internal/cli/clients/install_client.go
  internal/cli/config.go
  internal/cli/install.go
  internal/cli/root.go
Labels: documentation, enhancement, goobe, security

#521 fix: move traefik ingress class from label to annotation
  assets/embedded-files/tekton/pipeline.yaml
Labels: bug

#524 Basic notes and tips for installing on windows
  docs/windows.md
Labels: documentation, enhancement

#517 Support for disabling of color output
  acceptance/config_test.go
  internal/cli/config.go
  internal/cli/config/config.go
  internal/cli/root.go
Labels: enhancement, windows

#528 Fix bugs introduced by the `config update-credentials` work.
  internal/cli/clients/client.go
Labels: bug

#519 feat: reworked the docs for dev deployment
  docs/development.md
Labels: devops admin, documentation, enhancement

#535 Retry org creation when running into gateway and cert issues
  deployments/epinio.go
  internal/cli/clients/client.go
  internal/cli/config/config.go
  internal/cli/install.go
  internal/duration/duration.go
Labels: bug

#539 fix: Drop general silencing of the usage display on cli command line errors
  internal/cli/apps.go
  internal/cli/config.go
  internal/cli/delete.go
  internal/cli/disable.go
  internal/cli/enable.go
  internal/cli/info.go
  internal/cli/install.go
  internal/cli/orgs.go
  internal/cli/push.go
  internal/cli/server.go
  internal/cli/service.go
  internal/cli/target.go
  internal/cli/uninstall.go
Labels: bug, enhancement

#545 feat: Show warning as part of `enable services-incluster`, about the delays to expect.
  acceptance/utilities_test.go
  internal/cli/enable.go
Labels: enhancement, ux

#543 feat: Report already bound services as notes, not errors
  acceptance/api_v1_services_mutation_test.go
  internal/api/v1/models/models.go
  internal/api/v1/servicebindings.go
  internal/cli/clients/client.go
Labels: enhancement

#546 fix: missing container include/exclude checks in FetchLogs
  acceptance/apps_test.go
  helpers/kubernetes/tailer/setup.go
Labels: bug

#552 fix: give eventually more time in stronger adverse conditions
  acceptance/bindings_test.go
Labels: bug
