Repository epinio/epinio, pull requests merged in 2021-08, with the labels that each got.

#656 Fix app ingress secret mismatch
  Makefile
  internal/api/v1/deploy.go
Labels: bug

#663 chore fix: Reworked infrastructure for shelling out, prevent quoting issues
  acceptance/api/v1/applications_test.go
  acceptance/api/v1/orgs_test.go
  acceptance/api/v1/services_mutation_test.go
  acceptance/api/v1/suite_test.go
  acceptance/apps_env_test.go
  acceptance/apps_test.go
  acceptance/bindings_test.go
  acceptance/catalog_services_test.go
  acceptance/config_test.go
  acceptance/custom_services_test.go
  acceptance/epinio_installation_test.go
  acceptance/helpers/epinio/epinio.go
  acceptance/helpers/machine/apps.go
  acceptance/helpers/machine/machine.go
  acceptance/helpers/machine/services.go
  acceptance/helpers/proc/proc.go
  acceptance/install/config_test.go
  acceptance/orgs_test.go
  acceptance/rails_test.go
  acceptance/service_classes_test.go
  acceptance/services_test.go
  acceptance/suite_test.go
  acceptance/testenv/epinio.go
  acceptance/testenv/google.go
  acceptance/testenv/patch.go
  acceptance/testenv/registry.go
  acceptance/testenv/services.go
  acceptance/testenv/tmpdir.go
  acceptance/wordpress_test.go
  deployments/cert_manager.go
  deployments/epinio.go
  deployments/gitea.go
  deployments/google_services.go
  deployments/kubed.go
  deployments/minibroker.go
  deployments/registry.go
  deployments/service_catalog.go
  deployments/tekton.go
  deployments/traefik.go
  helpers/embedded_files.go
  helpers/exec.go
  internal/cli/clients/install_client.go
Labels: enhancement, wip, chore, windows, portability

#671 Cluster patching for Windows. Plus documentation.
  Makefile
  docs/developer/howtos/development.md
  go.mod
  go.sum
  helpers/termui/ui.go
  internal/cli/clients/install_client.go
  internal/cli/debug.go
  internal/cli/root.go
  scripts/patch-epinio-deployment.sh
Labels: bug, windows, portability

#678 Increase default deployment installation timeout
  assets/embedded-files/linkerd/install-job.yaml
  assets/embedded-files/linkerd/uninstall-job.yaml
  deployments/linkerd.go
  internal/duration/duration.go
Labels: bug

#685 Improve inline documentation of the "server" command
  Makefile
  docs/user/references/cli/epinio.md
  docs/user/references/cli/epinio_server.md
  docs/user/tutorials/install_epinio_on_k3d.md
  internal/cli/server.go
Labels: documentation

#664 More installer tests
  .github/workflows/main.yml
  Makefile
  acceptance/api/v1/applications_test.go
  acceptance/api/v1/suite_test.go
  acceptance/helpers/epinio/epinio.go
  acceptance/helpers/proc/proc.go
  acceptance/install/config_test.go
  acceptance/install/java_app_with_service_test.go
  acceptance/install/rails_app_with_env_test.go
  acceptance/install/split_traefik_test.go
  acceptance/install/suite_test.go
  acceptance/suite_test.go
  acceptance/testenv/download.go
  acceptance/testenv/env.go
  acceptance/testenv/epinio.go
  acceptance/testenv/google.go
  acceptance/testenv/root.go
  acceptance/testenv/services.go
  assets/tests/cluster-issuer-private-ca.yml
  assets/tests/sample-app.tar
  assets/tests/untar.tgz
  helpers/helpers_suite_test.go
  helpers/untar_test.go
Labels: enhancement, devops admin, installation

#692 Caching api/wss urls in the configuration
  acceptance/config_test.go
  acceptance/helpers/machine/machine.go
  docs/user/explanations/configuration.md
  docs/user/references/cli/epinio_config.md
  docs/user/references/cli/epinio_config_update.md
  internal/cli/apps.go
  internal/cli/clients/client.go
  internal/cli/clients/epinio_api.go
  internal/cli/config.go
  internal/cli/config/config.go
  internal/cli/debug.go
  internal/cli/disable.go
  internal/cli/enable.go
  internal/cli/env.go
  internal/cli/orgs.go
  internal/cli/service.go
Labels: enhancement

#695 EKS Documentation
  README.md
  docs/user/tutorials/install_epinio_on_eks.md
Labels: documentation

#700 Prefix app service and ingress names to ensure validity as a kube resource name
  acceptance/apps_test.go
  acceptance/wordpress_test.go
  helpers/kubernetes/cluster.go
  internal/api/v1/deploy.go
  internal/application/workload.go
  internal/names/names.go
Labels: bug

#701 688 cache image
  acceptance/apps_test.go
  assets/embedded-files/epinio/server.yaml
  assets/embedded-files/tekton/stage-pipeline.yaml
  internal/api/v1/models/app.go
  internal/api/v1/stage.go
  internal/application/application.go
Labels: enhancement, performance

#694 No longer copy epinio config/binary to ginkgo node tmp dir
  acceptance/api/v1/applications_test.go
  acceptance/api/v1/suite_test.go
  acceptance/apps_test.go
  acceptance/helpers/machine/machine.go
  acceptance/install/suite_test.go
  acceptance/rails_test.go
  acceptance/suite_test.go
  acceptance/testenv/epinio.go
  acceptance/testenv/tmpdir.go
Labels: devops admin

#705 Updates to the config docs to mention the newly stored api urls
  docs/user/explanations/configuration.md
Labels: documentation, chore

#709 Identify slow CLI tests
  Makefile
Labels: chore

#708 Remove direct kube access from client commands.
  acceptance/api/v1/applications_test.go
  helpers/kubernetes/cluster.go
  internal/api/v1/applications.go
  internal/api/v1/deploy.go
  internal/api/v1/info.go
  internal/api/v1/models/models.go
  internal/api/v1/router.go
  internal/api/v1/stage.go
  internal/cli/clients/client.go
  internal/cli/clients/push.go
  internal/domain/domain.go
  internal/web/info_controller.go
Labels: chore

#714 Split Application Acceptance Tests
  .github/workflows/main.yml
  Makefile
  acceptance/apps/rails_test.go
  acceptance/apps/suite_test.go
  acceptance/apps/wordpress_test.go
Labels: devops admin, chore

#718 feat: provide user information to the api server
  acceptance/config_test.go
  acceptance/helpers/catalog/names.go
  assets/embedded-files/epinio/basicauth.yaml
  assets/embedded-files/epinio/server.yaml
  docs/developer/howtos/README.md
  docs/developer/howtos/new-api-user.md
  internal/cli/clients/client.go
  internal/cli/config.go
  internal/cli/config/config.go
  internal/cli/server.go
Labels: documentation, enhancement

#704 Give gitea's postgresql container sufficient permissions
  deployments/gitea.go
Labels: bug, safe to test

#731 Folded `behind the curtains` text into the single howto referencing it
  docs/developer/howtos/README.md
  docs/developer/howtos/behind-the-curtains.md
  docs/developer/howtos/development.md
Labels: bug, documentation

#726 chore: extend the code documentation
  internal/api/v1/applications.go
  internal/api/v1/deploy.go
  internal/api/v1/env.go
  internal/api/v1/errors.go
  internal/api/v1/info.go
  internal/api/v1/models/app.go
  internal/api/v1/models/env.go
  internal/api/v1/models/models.go
  internal/api/v1/models/sort.go
  internal/api/v1/organizations.go
  internal/api/v1/router.go
  internal/api/v1/servicebindings.go
  internal/api/v1/serviceclasses.go
  internal/api/v1/serviceplans.go
  internal/api/v1/services.go
  internal/api/v1/stage.go
  internal/api/v1/upload.go
  internal/application/application.go
  internal/application/env.go
  internal/application/workload.go
  internal/auth/auth.go
  internal/auth/certs.go
  internal/cli/apps.go
  internal/cli/commons.go
  internal/cli/config.go
  internal/cli/debug.go
  internal/cli/delete.go
  internal/cli/disable.go
  internal/cli/enable.go
  internal/cli/env.go
  internal/cli/info.go
  internal/cli/install.go
  internal/cli/orgs.go
  internal/cli/push.go
  internal/cli/root.go
  internal/cli/server.go
  internal/cli/service.go
  internal/cli/target.go
  internal/cli/uninstall.go
  internal/domain/domain.go
  internal/duration/duration.go
  internal/filesystem/filesystem.go
  internal/interfaces/interfaces.go
  internal/names/names.go
  internal/organizations/organizations.go
  internal/services/catalog_service.go
  internal/services/custom_service.go
  internal/services/services.go
  internal/version/version.go
  internal/web/applications_controller.go
  internal/web/info_controller.go
  internal/web/orgs_controller.go
  internal/web/router.go
Labels: documentation, enhancement, chore

#733 Enable gitea volume permissions
  deployments/gitea.go
Labels: bug, safe to test

#735 Tweak the changelog generator's configuration
  .github/workflows/release.yml
Labels: enhancement
