Repository epinio/epinio, pull requests merged in 2021-02, with the labels that each got.

#96 Added dev-level tracing
  cli/cmd/internal/client/install.go
  cli/cmd/root.go
  cli/go.mod
  cli/go.sum
  cli/kubernetes/config/logger.go
  cli/paas/client.go
  cli/paas/install_client.go
  cli/paas/wire.go
  cli/paas/wire_gen.go
Labels: enhancement, goobe

#148 Enforce conventional commits
  .github/workflows/lint_commit_messages.yml
  .github/workflows/release.yml
  .gitlint
  Makefile
  docs/development.md
Labels: devops admin, enhancement

#153 Fix changelog generation
  .github/workflows/release.yml
Labels: devops admin

#163 fix: binary version of `carrier`
  .github/workflows/main.yml
  .gitignore
  Makefile
  cmd/root.go
Labels: bug
