Repository epinio/epinio, pull requests merged in 2021-09, with the labels that each got.

#734 Mostly more tracing the log streaming facilities, plus bug fix for install
  helpers/kubernetes/tailer/setup.go
  helpers/kubernetes/tailer/watcher.go
  internal/api/v1/applications.go
  internal/application/application.go
  internal/cli/clients/client.go
Labels: bug, enhancement

#742 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ux

#739 Org becomes Namespace
  Makefile
  acceptance/api/v1/applications_test.go
  acceptance/api/v1/orgs_test.go
  acceptance/api/v1/services_mutation_test.go
  acceptance/api/v1/services_test.go
  acceptance/config_test.go
  acceptance/helpers/catalog/names.go
  acceptance/helpers/machine/machine.go
  acceptance/install/config_test.go
  acceptance/install/scenario4_test.go
  acceptance/install/split_traefik_test.go
  acceptance/orgs_test.go
  acceptance/testenv/epinio.go
  assets/embedded-web-files/assets/js/applications.js
  assets/embedded-web-files/views/modals.html
  docs/developer/howtos/development.md
  docs/user/explanations/configuration.md
  docs/user/references/README.md
  docs/user/references/cli/epinio.md
  docs/user/references/cli/epinio_app.md
  docs/user/references/cli/epinio_app_env.md
  docs/user/references/cli/epinio_config.md
  docs/user/references/cli/epinio_disable.md
  docs/user/references/cli/epinio_enable.md
  docs/user/references/cli/epinio_install.md
  docs/user/references/cli/epinio_namespace.md
  docs/user/references/cli/epinio_namespace_create.md
  docs/user/references/cli/epinio_namespace_delete.md
  docs/user/references/cli/epinio_namespace_list.md
  docs/user/references/cli/epinio_service.md
  docs/user/references/cli/epinio_target.md
  docs/user/tutorials/quickstart.md
  helpers/kubernetes/cluster.go
  internal/api/v1/errors.go
  internal/api/v1/models/app.go
  internal/api/v1/organizations.go
  internal/api/v1/router.go
  internal/application/application.go
  internal/cli/clients/client.go
  internal/cli/config.go
  internal/cli/config/config.go
  internal/cli/install.go
  internal/cli/orgs.go
  internal/cli/target.go
  internal/organizations/organizations.go
  internal/services/catalog_service.go
  internal/services/custom_service.go
  internal/web/applications_controller.go
Labels: chore

#751 Org/Namespace followup: Fixed missed old option in scenario tests
  acceptance/install/scenario3_test.go
Labels: bug

#749 Check for and report errors for "epinio info"
  docs/user/references/cli/epinio_info.md
  internal/cli/clients/client.go
Labels: safe to test

#753 Improve user facing error messages
  acceptance/api/v1/services_mutation_test.go
  internal/api/v1/errors.go
  internal/cli/clients/client.go
Labels: enhancement, goobe, ux

#754 Fix parameter config for changelog generator action
  .github/workflows/release.yml
Labels: bug

#755 Fix second parameter which really should take a sequence and doesn't.
  .github/workflows/release.yml
Labels: bug

#756 fix: revert introduction of `issueLineLabels`.
  .github/workflows/release.yml
Labels: bug

#767 Fix to use namespace key for default namespace
  internal/cli/config/config.go
Labels: chore

#776 Add troubleshoot section for DNS rebinding
  docs/user/tutorials/install_epinio_magicDNS.md
Labels: documentation

#770 More tracing
  internal/cli/clients/client.go
  internal/cli/clients/epinio_api.go
  internal/cli/clients/install_client.go
  internal/cli/config/config.go
  internal/cli/install.go
Labels: bug

#778 Install sets epinio timeout multiplier on server
  assets/embedded-files/epinio/server.yaml
  deployments/epinio.go
  internal/cli/config.go
Labels: chore

#780 Small docs improvements
  README.md
Labels: documentation

#777 Remove kubectl/curl/helm from base image
  .dockerignore
  images/Dockerfile
  images/baseimage-Dockerfile
  internal/cli/install.go
  internal/cli/root.go
  internal/cli/uninstall.go
Labels: chore

#779 Safety: Report empty namespace.
  internal/cli/clients/client.go
Labels: ux

#797 Add documentation for default storage class
  README.md
  docs/user/tutorials/install_epinio_customDNS.md
  docs/user/tutorials/install_epinio_magicDNS.md
Labels: documentation

#796 API: Extended namespace listing, namespace matching
  acceptance/api/v1/orgs_test.go
  internal/api/v1/models/namespace.go
  internal/api/v1/organizations.go
  internal/api/v1/router.go
  internal/cli/clients/client.go
  internal/cli/orgs.go
  internal/cli/root.go
Labels: bug, enhancement, api

#788 699 remove gitea
  acceptance/api/v1/applications_test.go
  acceptance/testenv/epinio.go
  assets/embedded-files/minio/operator.yaml
  assets/embedded-files/minio/tenant.yaml
  assets/embedded-files/tekton/admin-role.yaml
  assets/embedded-files/tekton/aws-cli-0.2.yaml
  assets/embedded-files/tekton/stage-pipeline.yaml
  assets/embedded-web-files/views/info.html
  deployments/gitea.go
  deployments/minio.go
  deployments/tekton.go
  docs/user/explanations/advanced.md
  go.mod
  go.sum
  helpers/tar.go
  internal/api/v1/applications.go
  internal/api/v1/deploy.go
  internal/api/v1/importgit.go
  internal/api/v1/models/app.go
  internal/api/v1/models/models.go
  internal/api/v1/organizations.go
  internal/api/v1/router.go
  internal/api/v1/stage.go
  internal/api/v1/upload.go
  internal/application/application.go
  internal/cli/clients/client.go
  internal/cli/clients/gitea/gitea.go
  internal/cli/clients/gitea/upload.go
  internal/cli/clients/install_client.go
  internal/cli/clients/push.go
  internal/cli/info.go
  internal/cli/install.go
  internal/organizations/organizations.go
  internal/s3manager/s3manager.go
  internal/s3manager/s3manager_test.go
  internal/s3manager/suite_test.go
  internal/web/info_controller.go
Labels: enhancement, beta2

#800 Fetch apps across all epinio-controlled namespaces
  acceptance/api/v1/applications_test.go
  acceptance/apps_test.go
  acceptance/helpers/machine/machine.go
  internal/api/v1/applications.go
  internal/api/v1/router.go
  internal/cli/apps.go
  internal/cli/clients/client.go
Labels: enhancement, api, beta2

#831 Wait until CRDs are also established
  helpers/kubernetes/cluster.go
Labels: bug

#803 Support binding services to apps at rest
  Makefile
  acceptance/api/v1/applications_test.go
  acceptance/api/v1/services_mutation_test.go
  acceptance/apps_test.go
  acceptance/catalog_services_test.go
  acceptance/custom_services_test.go
  docs/developer/explanations/service-management-internals.md
  internal/api/v1/applications.go
  internal/api/v1/deploy.go
  internal/api/v1/env.go
  internal/api/v1/servicebindings.go
  internal/api/v1/services.go
  internal/api/v1/stage.go
  internal/application/application.go
  internal/application/env.go
  internal/application/scale.go
  internal/application/services.go
  internal/application/workload.go
  internal/cli/apps.go
  internal/cli/options.go
  internal/cli/push.go
  internal/cli/usercmd/apps_create.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/push.go
  internal/interfaces/interfaces.go
  internal/services/catalog_service.go
  internal/services/custom_service.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/models/app.go
  pkg/api/core/v1/models/env.go
  pkg/api/core/v1/models/models.go
Labels: enhancement, ux, api, beta2

#838 Update scripts for gh action runners
  scripts/remove-github-action-runner.sh
  scripts/setup-github-action-runner.sh
Labels: safe to test

#845 fix: Ensure tests can use EPINIO_CONFIG env variable
  acceptance/testenv/epinio.go
Labels: devops admin
