Repository epinio/epinio, pull requests merged in 2021-11, with the labels that each got.

#962 Enable cross CI to release helm chart
  .github/workflows/release.yml
Labels: devops admin

#964 Find certificate with selector - part 2
  acceptance/install/scenario2_test.go
  acceptance/install/scenario5_test.go
Labels: QA

#960 Add Mac M1 silicon (Darwin/ARM64) support to Makefile
  Makefile
Labels: macOS

#956 Installer waits for minio tenant to be ready
  deployments/cert_manager.go
  deployments/epinio.go
  deployments/minio.go
  deployments/tekton.go
  deployments/traefik.go
  helpers/kubernetes/cluster.go
Labels: bug

#963 Add a purge step in CI tests when route53 is used
  acceptance/helpers/route53/change.go
  acceptance/install/scenario2_test.go
  acceptance/install/scenario4_test.go
  acceptance/install/scenario5_test.go
Labels: QA

#955 Save routes to manifest. Show routes in app details
  acceptance/apps_test.go
  internal/api/v1/response/response.go
  internal/application/application.go
  internal/application/ingresses.go
  internal/cli/usercmd/app.go
Labels: bug

#970 feat: CORS
  assets/embedded-files/epinio/server.yaml
  deployments/epinio.go
  internal/cli/install.go
  internal/cli/server.go
  internal/cli/server/server.go
Labels: enhancement, beta2

#973 Add Additional CORS headers
  internal/cli/server/server.go
Labels: beta2

#978 CLI doc generation script, and hugo fixup
  Makefile
  scripts/cli-docs-generate.sh
Labels: chore

#972 Add initial swagger spec generation for API docs
  .github/workflows/aks.yml
  .github/workflows/eks.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/outside-pr.yml
  .github/workflows/release.yml
  .github/workflows/rke.yml
  Makefile
  docs/references/api/swagger.json
  internal/api/v1/docs/application.go
  internal/api/v1/docs/env.go
  internal/api/v1/docs/info.go
  internal/api/v1/docs/namespace.go
  internal/api/v1/docs/service.go
  internal/api/v1/docs/servicebinding.go
  internal/api/v1/router.go
Labels: documentation, enhancement, api, beta2

#993 991 app images
  internal/api/v1/application/stage.go
Labels: bug, beta2

#1002 Fix CI trigger on AKS, EKS, GKE and RKE
  .github/workflows/aks.yml
  .github/workflows/eks.yml
  .github/workflows/gke.yml
  .github/workflows/rke.yml
Labels: QA

#980 Persist app origin information to App CRD resource
  Makefile
  acceptance/api/v1/applications_test.go
  acceptance/apps_test.go
  assets/embedded-files/epinio/app-crd.yaml
  docs/references/api/swagger.json
  go.mod
  go.sum
  internal/api/v1/application/deploy.go
  internal/application/application.go
  internal/application/origin.go
  internal/cli/usercmd/app.go
  internal/cli/usercmd/push.go
  pkg/api/core/v1/models/app.go
  pkg/api/core/v1/models/models.go
  scripts/prepare-environment-k3d.sh
  scripts/update-app-crd.sh
Labels: enhancement

#1004 Bump mholt/archiver to v3.5.1
  go.mod
  go.sum
Labels: beta2

#1010 Add external registry test
  .github/workflows/rke.yml
  acceptance/install/scenario3_test.go
Labels: QA

#1014 Remodeled service responses
  acceptance/api/v1/services_test.go
  docs/references/api/swagger.json
  internal/api/v1/service/delete.go
  internal/api/v1/service/fullindex.go
  internal/api/v1/service/index.go
  internal/api/v1/service/serviceapps.go
  internal/api/v1/service/show.go
  internal/application/application.go
  internal/application/env.go
  internal/application/scale.go
  internal/application/services.go
  internal/cli/usercmd/service.go
  pkg/api/core/v1/models/models.go
Labels: bug, milestone3

#1021 small fix: followup to PR 1014, regenerate swagger docs
  docs/references/api/swagger.json
Labels: bug, documentation

#1015 Validate blob issued to staging (must match app)
  acceptance/api/v1/applications_test.go
  internal/api/v1/application/stage.go
  internal/s3manager/s3manager.go
Labels: enhancement
