Repository epinio/epinio, pull requests merged in 2021-04, with the labels that each got.

#278 Fixed file name still using carrier
  docs/epinio-push.svg
Labels: bug, documentation

#280 Switch commands using the API from local server to server in the cluster
  acceptance/acceptance_suite_test.go
  acceptance/orgs_test.go
  deployments/epinio.go
  embedded-files/epinio/server.yaml
  internal/cli/apps.go
  internal/cli/clients/client.go
  internal/cli/clients/epinio_api.go
  internal/cli/clients/gitea.go
  internal/cli/config/config.go
  internal/cli/create_org.go
  internal/cli/delete.go
  internal/cli/install.go
  internal/cli/orgs.go
  statik/statik.go
Labels: chore, enhancement

#311 306 documentation improvements
  README.md
Labels: documentation

#315 fix: ginkgo location printing from suite utility functions
  acceptance/catalog_services_test.go
  acceptance/custom_services_test.go
  acceptance/utilities_test.go
Labels: devops admin

#316 fix: extended reporting for quarks install failures
  deployments/quarks.go
Labels: enhancement, ux

#340 Remove openssl dependency
  assets/container-registry/chart/container-registry/templates/container-registry.yaml
  assets/embedded-files/container-registry-0.1.0.tgz
  assets/embedded-files/tekton/staging.yaml
  deployments/tekton.go
  internal/cli/root.go
Labels: enhancement

#341 fix: remove superfluous function
  helpers/exec.go
Labels: bug
