Repository epinio/epinio, pull requests merged in 2021-07, with the labels that each got.

#558 fix: attempt to retrieve stage id of an app without workload
  acceptance/apps_test.go
  helpers/kubernetes/cluster.go
  internal/application/workload.go
Labels: bug

#565 Deploy from GIT url
  acceptance/apps_test.go
  internal/api/v1/stage.go
  internal/api/v1/upload.go
  internal/cli/clients/client.go
  internal/cli/push.go
Labels: enhancement

#568 Dynamic silence and ingress type
  assets/container-registry/chart/container-registry/templates/container-registry.yaml
  assets/embedded-files/epinio/server.yaml
  deployments/epinio.go
  helpers/kubernetes/cluster.go
  internal/cli/apps.go
Labels: bug

#579 CI ignores changes to README.md
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/outside-pr.yml
Labels: bug

#580 CI: Concurrent jobs to run the acceptance test api, cli suites
  .github/workflows/main.yml
  Makefile
  scripts/acceptance-cluster-setup.sh
Labels: devops admin, enhancement

#587 Support App environment Variables
  Makefile
  acceptance/apps_env_test.go
  assets/embedded-files/tekton/pipeline.yaml
  internal/api/v1/applications.go
  internal/api/v1/env.go
  internal/api/v1/models/app.go
  internal/api/v1/models/env.go
  internal/api/v1/router.go
  internal/api/v1/stage.go
  internal/application/application.go
  internal/application/env.go
  internal/application/workload.go
  internal/cli/apps.go
  internal/cli/clients/client.go
  internal/cli/env.go
Labels: enhancement

#607 Extended org creation retry
  internal/cli/clients/client.go
Labels: chore, enhancement

#614 Update docs for tls-issuer arg
  Makefile
  README.md
  deployments/epinio.go
  deployments/registry.go
  docs/README.md
  docs/developer/howtos/custom-python-builder.md
  docs/user/explanations/configuration.md
  docs/user/explanations/detailed-push-process.md
  docs/user/howtos/certificate_issuers.md
  docs/user/howtos/provision_external_ip_for_local_kubernetes.md
  docs/user/references/cli/epinio.md
  docs/user/references/cli/epinio_app.md
  docs/user/references/cli/epinio_app_create.md
  docs/user/references/cli/epinio_app_delete.md
  docs/user/references/cli/epinio_app_env.md
  docs/user/references/cli/epinio_app_env_list.md
  docs/user/references/cli/epinio_app_env_set.md
  docs/user/references/cli/epinio_app_env_show.md
  docs/user/references/cli/epinio_app_env_unset.md
  docs/user/references/cli/epinio_app_list.md
  docs/user/references/cli/epinio_app_logs.md
  docs/user/references/cli/epinio_app_show.md
  docs/user/references/cli/epinio_app_update.md
  docs/user/references/cli/epinio_completion.md
  docs/user/references/cli/epinio_config.md
  docs/user/references/cli/epinio_config_colors.md
  docs/user/references/cli/epinio_config_show.md
  docs/user/references/cli/epinio_config_update-credentials.md
  docs/user/references/cli/epinio_disable.md
  docs/user/references/cli/epinio_disable_services-google.md
  docs/user/references/cli/epinio_disable_services-incluster.md
  docs/user/references/cli/epinio_enable.md
  docs/user/references/cli/epinio_enable_services-google.md
  docs/user/references/cli/epinio_enable_services-incluster.md
  docs/user/references/cli/epinio_info.md
  docs/user/references/cli/epinio_install-ingress.md
  docs/user/references/cli/epinio_install.md
  docs/user/references/cli/epinio_org.md
  docs/user/references/cli/epinio_org_create.md
  docs/user/references/cli/epinio_org_delete.md
  docs/user/references/cli/epinio_org_list.md
  docs/user/references/cli/epinio_push.md
  docs/user/references/cli/epinio_server.md
  docs/user/references/cli/epinio_service.md
  docs/user/references/cli/epinio_service_bind.md
  docs/user/references/cli/epinio_service_create-custom.md
  docs/user/references/cli/epinio_service_create.md
  docs/user/references/cli/epinio_service_delete.md
  docs/user/references/cli/epinio_service_list-classes.md
  docs/user/references/cli/epinio_service_list-plans.md
  docs/user/references/cli/epinio_service_list.md
  docs/user/references/cli/epinio_service_show.md
  docs/user/references/cli/epinio_service_unbind.md
  docs/user/references/cli/epinio_target.md
  docs/user/references/cli/epinio_uninstall.md
  docs/user/references/cli/epinio_version.md
  docs/user/tutorials/install_epinio_on_gke.md
  docs/user/tutorials/install_epinio_on_k3d.md
  internal/cli/docs/generate-cli-docs.go
  internal/cli/install.go
Labels: documentation

#617 Explain --use-internal-registry-node-port=false
  docs/user/howtos/certificate_issuers.md
Labels: documentation

#596 Fix error message when Traefik fails to get an IP
  deployments/traefik.go
Labels: safe to test

#621 Remove unused pflags arg
  internal/cli/apps.go
  internal/cli/clients/client.go
  internal/cli/config.go
  internal/cli/delete.go
  internal/cli/env.go
  internal/cli/info.go
  internal/cli/install.go
  internal/cli/orgs.go
  internal/cli/push.go
  internal/cli/service.go
  internal/cli/target.go
  internal/web/info_controller.go
Labels: chore

#619 Allow mounting of the SA for linkerd sidecars in app pods
  assets/embedded-files/tekton/pipeline.yaml
  internal/organizations/organizations.go
Labels: bug, enhancement, security

#624 Fix command completion crashes
  internal/cli/apps.go
  internal/cli/delete.go
  internal/cli/env.go
  internal/cli/service.go
  internal/cli/target.go
Labels: bug, ux

#632 Add make install target
  Makefile
  docs/developer/howtos/behind-the-curtains.md
  docs/developer/howtos/development.md
Labels: safe to test
