Repository epinio/epinio, pull requests merged in 2021-10, with the labels that each got.

#849 Drop developers/ prefix from docs structure
  docs/README.md
  docs/explanations/futureplans.md
  docs/explanations/service-management-internals.md
  docs/howtos/README.md
  docs/howtos/acceptance_tests.md
  docs/howtos/custom-python-builder.md
  docs/howtos/development.md
  docs/howtos/new-api-user.md
Labels: documentation

#858 chore: cleanup of the services code with catalog gone
  acceptance/api/v1/applications_test.go
  acceptance/api/v1/orgs_test.go
  acceptance/api/v1/services_mutation_test.go
  acceptance/api/v1/services_test.go
  acceptance/apps/rails_test.go
  acceptance/apps_test.go
  acceptance/bindings_test.go
  acceptance/custom_services_test.go
  acceptance/helpers/machine/services.go
  acceptance/install/scenario3_test.go
  acceptance/services_test.go
  internal/api/v1/deploy.go
  internal/api/v1/router.go
  internal/api/v1/servicebindings.go
  internal/api/v1/services.go
  internal/application/services.go
  internal/application/workload.go
  internal/cli/service.go
  internal/cli/usercmd/client.go
  internal/interfaces/interfaces.go
  internal/services/custom_service.go
  internal/services/services.go
  pkg/api/core/v1/client/services.go
  pkg/api/core/v1/models/models.go
Labels: chore

#850 Labeled secrets in a single step (just creation)
  helpers/kubernetes/cluster.go
  internal/application/env.go
  internal/application/scale.go
  internal/application/services.go
Labels: chore

#741 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ux

#848 Show path information for service parameters
  internal/api/v1/services.go
  internal/cli/usercmd/client.go
  pkg/api/core/v1/models/models.go
Labels: enhancement, goobe, ux

#866 Fix readmes and docs content
  README.md
  docs/howtos/development.md
Labels: bug, documentation

#862 Improvements from Helm Deployment Spike
  assets/embedded-files/tekton/stage-pipeline.yaml
  docs/howtos/development.md
  helpers/kubernetes/cluster.go
  internal/api/v1/applications.go
  internal/api/v1/deploy.go
  internal/api/v1/router.go
  internal/api/v1/stage.go
  internal/application/application.go
Labels: chore

#863 Add retry to API client
  .github/ISSUE_TEMPLATE/bug_report.md
  helpers/error.go
  internal/api/v1/router.go
  internal/cli/usercmd/apps_create.go
  internal/cli/usercmd/push.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/http.go
  pkg/api/core/v1/client/namespaces.go
Labels: chore
