Repository epinio/epinio, pull requests merged in 2022-09, with the labels that each got.

#1705 Squash all golang-ci linter reports
  acceptance/api/v1/appchart_index_test.go
  acceptance/api/v1/appchart_match_test.go
  acceptance/api/v1/appchart_show_test.go
  acceptance/api/v1/application_create_test.go
  acceptance/api/v1/application_delete_test.go
  acceptance/api/v1/application_export_test.go
  acceptance/api/v1/application_importgit_test.go
  acceptance/api/v1/application_index_all_test.go
  acceptance/api/v1/application_index_test.go
  acceptance/api/v1/application_logs_test.go
  acceptance/api/v1/application_match_test.go
  acceptance/api/v1/application_portforward_test.go
  acceptance/api/v1/application_restart_test.go
  acceptance/api/v1/application_show_test.go
  acceptance/api/v1/application_stage_test.go
  acceptance/api/v1/application_update_test.go
  acceptance/api/v1/application_upload_test.go
  acceptance/api/v1/configuration_match_test.go
  acceptance/api/v1/configurations_mutation_test.go
  acceptance/api/v1/configurations_test.go
  acceptance/api/v1/helpers_test.go
  acceptance/api/v1/namespace_delete_test.go
  acceptance/api/v1/namespaces_test.go
  acceptance/api/v1/service_bind_test.go
  acceptance/api/v1/service_create_test.go
  acceptance/api/v1/service_delete_test.go
  acceptance/api/v1/service_match_test.go
  acceptance/api/v1/service_show_test.go
  acceptance/api/v1/services_catalog_match_test.go
  acceptance/api/v1/services_catalog_test.go
  acceptance/api/v1/suite_test.go
  acceptance/apps/rails_test.go
  acceptance/apps/suite_test.go
  acceptance/apps/wordpress_test.go
  acceptance/apps_test.go
  acceptance/helpers/machine/machine.go
  acceptance/helpers/route53/change.go
  acceptance/settings_test.go
  acceptance/suite_test.go
  acceptance/testenv/sleep.go
  acceptance/upgrade/suite_test.go
  helpers/exec.go
  helpers/tar.go
  internal/api/v1/application/importgit.go
  internal/api/v1/application/part.go
  internal/api/v1/deploy/deploy.go
  internal/api/v1/docs/docs.go
  internal/application/application.go
  internal/cli/docs/generate-cli-docs.go
  internal/cli/server.go
  internal/cli/usercmd/app.go
  internal/manifest/manifest.go
  internal/manifest/manifest_test.go
  internal/registry/registry.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/http.go
Labels: chore

#1725 fix tests often stuck and failing
  acceptance/apps_test.go
  acceptance/helpers/machine/apps.go
Labels: bug

#1735 Block `configuration unbind|delete` for service-owned configurations
  acceptance/api/v1/application_export_test.go
  acceptance/api/v1/configurations_mutation_test.go
  acceptance/apps_test.go
  acceptance/configurations_test.go
  internal/api/v1/configuration/delete.go
  internal/api/v1/configurationbinding/delete.go
  internal/api/v1/configurationbinding/deletebinding.go
  internal/api/v1/service/unbind.go
  internal/cli/usercmd/configuration.go
Labels: bug

#1747 added workflow to build and publish the epinio-unpacker image supporting the unpack step of epinio staging
  .github/workflows/unpacker-image.yml
  images/unpacker-Dockerfile
Labels: chore

#1575 Epinio new releases sent dispatch event to epinio/docs
  .github/workflows/release.yml
Labels: release
