Repository epinio/epinio, pull requests merged in 2022-01, with the labels that each got.

#1110 Better match GET service to GET services.
  acceptance/api/v1/services_test.go
  docs/references/api/swagger.json
  internal/api/v1/docs/service.go
  internal/api/v1/service/show.go
  internal/cli/usercmd/service.go
  pkg/api/core/v1/client/services.go
Labels: bug, api

#1120 fix: unwanted retry of `namespace create` for existing namespace
  pkg/api/core/v1/client/namespaces.go
Labels: bug

#1133 Fix RKE2 installation for CI
  .github/workflows/rke.yml
Labels: QA

#1134 Centralize duplicated code
  internal/cli/apps.go
  internal/cli/commons.go
  internal/cli/delete.go
  internal/cli/env.go
  internal/cli/namespaces.go
  internal/cli/service.go
  internal/cli/target.go
  internal/cli/usercmd/app.go
Labels: chore

#1126 fix: defend against bad path names
  helpers/untar.go
  helpers/untar_test.go
Labels: security

#1138 feat: stream uploaded app sources directly into s3, without temp file
  internal/api/v1/application/upload.go
  internal/s3manager/s3manager.go
Labels: enhancement, performance

#1135 Fix for windows paths
  internal/application/origin.go
  internal/application/origin_test.go
  internal/application/suite_test.go
  internal/cli/usercmd/push.go
  internal/manifest/manifest.go
  internal/manifest/manifest_test.go
  pkg/api/core/v1/models/app.go
  pkg/api/core/v1/models/models.go
Labels: bug

#1154 Remove unsed function 'assetPath' from helpers
  helpers/helpers_suite_test.go
Labels: QA

#1155 Use PHP 7.4 instead of 7.3 for wordpress testapp
  acceptance/apps/wordpress_test.go
Labels: QA
