Repository epinio/epinio, pull requests merged in 2022-02, with the labels that each got.

#1129 fix: missing build of local helm-charts for public cloud CI
  .github/workflows/aks.yml
  .github/workflows/eks.yml
  .github/workflows/gke.yml
  .github/workflows/rke.yml
  acceptance/helpers/epinio/epinio.go
  acceptance/install/scenario2_test.go
  acceptance/install/scenario3_test.go
  acceptance/install/scenario4_test.go
  acceptance/install/scenario5_test.go
  scripts/get-free-ip.sh
  scripts/helpers.sh
  scripts/remove-helm-repos.sh
  scripts/setup-chart-museum.sh
Labels: devops admin, QA

#1159 Add auth token for websockets
  acceptance/api/v1/application_exec_test.go
  acceptance/api/v1/application_logs_test.go
  acceptance/api/v1/suite_test.go
  acceptance/helpers/machine/machine.go
  go.mod
  go.sum
  helpers/authtoken/suite_test.go
  helpers/authtoken/token.go
  helpers/authtoken/token_test.go
  helpers/tracelog/logger.go
  internal/api/v1/application/create.go
  internal/api/v1/authtoken.go
  internal/api/v1/router.go
  internal/cli/server/server.go
  internal/cli/usercmd/app.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/http.go
  pkg/api/core/v1/models/models.go
Labels: enhancement

#1187 Added graceful shutdown
  internal/cli/server.go
  internal/cli/server/server.go
Labels: chore

#1181 Allow re-staging when previous staging failed - job-based stager issue
  Makefile
  acceptance/api/v1/helpers_test.go
  helpers/kubernetes/cluster.go
  internal/api/v1/application/stage.go
  internal/application/application.go
Labels: bug

#1194 Support staging from zip and various compressed tar formats
  Makefile
  acceptance/api/v1/application_stage_test.go
  assets/tests/sample-app.zip
  internal/api/v1/application/stage.go
Labels: enhancement

#1197 tweak: format detection in staging.
  internal/api/v1/application/stage.go
Labels: chore

#1189 Try to deduplicate the staging logs display in tests
  acceptance/apps/rails_test.go
  acceptance/apps/wordpress_test.go
  acceptance/apps_env_test.go
  acceptance/apps_test.go
  acceptance/helpers/machine/apps.go
  acceptance/helpers/machine/machine.go
Labels: chore

#1202 Remove unused durations
  internal/duration/duration.go
Labels: chore

#1206 Add error to the Gin context
  internal/api/v1/response/response.go
Labels: bug

#1207 Mount CA & TLS in staging pod, not only the CA
  README.md
  internal/api/v1/application/stage.go
Labels: bug

#1208 Logging fixes
  go.mod
  go.sum
  helpers/kubernetes/tailer/setup.go
  helpers/kubernetes/tailer/watcher.go
  helpers/tracelog/logger.go
  internal/api/v1/application/deploy.go
  internal/api/v1/application/importgit.go
  internal/api/v1/application/logs.go
  internal/api/v1/application/stage.go
  internal/api/v1/application/upload.go
  internal/api/v1/env/index.go
  internal/api/v1/env/match.go
  internal/api/v1/env/set.go
  internal/api/v1/env/show.go
  internal/api/v1/env/unset.go
  internal/api/v1/namespace/match.go
  internal/api/v1/response/response.go
  internal/api/v1/router.go
  internal/application/application.go
  internal/application/ingresses.go
  internal/cli/server.go
  internal/cli/server/requestctx/context.go
  internal/cli/server/server.go
Labels: bug, chore

#1215 Return staging logs in order when fetched by `app logs` command
  helpers/kubernetes/tailer/setup.go
  helpers/kubernetes/tailer/tailer.go
  internal/application/application.go
Labels: bug

#1214 fix: missing update of the swagger
  docs/references/api/swagger.json
Labels: bug, chore

#1219 Add the client/server version of Epinio in `info`
  internal/cli/usercmd/info.go
Labels: enhancement

#1222 Add UI tests CI badges and rename some
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke.yml
  README.md
Labels: QA

#1227 Simplify CI and fix outside_pr CI
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/container-image-sample-app.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke.yml
  .github/workflows/main.yml
  .github/workflows/outside-pr.yml
  .github/workflows/rke.yml
  Makefile
Labels: QA

#1242 Linters refinement (dupl)
  .golangci.yml
  internal/application/env.go
  internal/application/scale.go
  internal/application/secret.go
  internal/application/services.go
Labels: chore

#1243 Add `--wait` option to Helm install/upgrade in CI
  acceptance/helpers/epinio/epinio.go
  acceptance/install/scenario1_test.go
  acceptance/install/scenario2_test.go
  acceptance/install/scenario3_test.go
  acceptance/install/scenario4_test.go
  acceptance/install/scenario5_test.go
  acceptance/install/scenario6_test.go
  acceptance/install/suite_test.go
Labels: QA

#1246 fix: always use latest eksctl for EKS-CI
  .github/workflows/eks.yml
Labels: QA

#1241 Logs cleanup
  helpers/tracelog/logger.go
  internal/cli/server.go
  internal/cli/server/server.go
  internal/cli/usercmd/client.go
  pkg/api/core/v1/client/http.go
Labels: chore
