Repository epinio/epinio, pull requests merged in 2022-04, with the labels that each got.

#1325 Update e2e badges status
  README.md
Labels: QA

#1334 Fix Github permissions
  .github/workflows/release.yml
  .goreleaser.yml
Labels: bug

#1336 Merge dependabot prs
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/container-image-sample-app.yml
  .github/workflows/container-images.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke.yml
  go.mod
  go.sum
Labels: chore

#1324 Implementation of `app export` command
  .github/workflows/golangci-lint.yml
  .golangci.yml
  acceptance/api/v1/application_export_test.go
  acceptance/apps_test.go
  acceptance/helpers/machine/apps.go
  docs/references/api/swagger.json
  internal/api/v1/application/part.go
  internal/api/v1/application/running.go
  internal/api/v1/docs/application.go
  internal/api/v1/response/response.go
  internal/api/v1/router.go
  internal/cli/apps.go
  internal/cli/usercmd/app.go
  internal/cli/usercmd/app_test.go
  internal/cli/usercmd/client.go
  internal/helm/helm.go
  pkg/api/core/v1/client/apps.go
Labels: enhancement

#1342 Add ginkgo info and make it verbose by default
  Makefile
  acceptance/install/suite_test.go
Labels: do not log

#1355 CatalogService converter
  go.mod
  go.sum
  internal/services/catalog.go
Labels: chore

#1366 Downgrade goreleaser to 1.7.0
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
Labels: chore

#1372 Cluster/Kubernetes helper cleanup
  helpers/kubernetes/cli_options_reader.go
  helpers/kubernetes/cli_options_reader_test.go
  helpers/kubernetes/cluster.go
  helpers/kubernetes/default_options_reader.go
  helpers/kubernetes/default_options_reader_test.go
  helpers/kubernetes/deployment.go
  helpers/kubernetes/installer_suite_test.go
  helpers/kubernetes/interactive_options_reader.go
  helpers/kubernetes/interactive_options_reader_test.go
  helpers/kubernetes/options.go
  helpers/kubernetes/options_test.go
  internal/application/application.go
  internal/auth/certs.go
Labels: chore

#1368 Pin goreleaser to 1.8.2 and fix #1365
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .goreleaser.yml
Labels: chore

#1385 Use external registry in all AKS tests
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  acceptance/install/scenario3_test.go
  acceptance/install/scenario5_test.go
  acceptance/install/scenario6_test.go
Labels: QA

#1387 Add swagger docs for `epinio service`
  docs/references/api/swagger.json
  internal/api/v1/docs/service.go
  internal/api/v1/router.go
  internal/api/v1/service/bind.go
  internal/api/v1/service/catalog.go
  internal/cli/services.go
Labels: documentation
