Repository epinio/epinio, pull requests merged in 2022-05, with the labels that each got.

#1394 E2e coverage
  .github/workflows/main.yml
  internal/cli/server.go
  main_test.go
  scripts/collect-coverage.sh
  scripts/patch-epinio-deployment.sh
  scripts/prepare-environment-k3d.sh
Labels: chore

#1401 Remove the create/delete operator actions from the `epinio app chart` ensemble.
  Makefile
  acceptance/api/v1/appchart_create_test.go
  acceptance/api/v1/appchart_delete_test.go
  acceptance/appcharts_test.go
  acceptance/apps_test.go
  docs/references/api/swagger.json
  internal/api/v1/appchart/create.go
  internal/api/v1/appchart/delete.go
  internal/api/v1/docs/appchart.go
  internal/api/v1/router.go
  internal/appchart/appchart.go
  internal/cli/chart.go
  internal/cli/usercmd/app_test.go
  internal/cli/usercmd/chart.go
  internal/cli/usercmd/client.go
  pkg/api/core/v1/client/chart.go
  pkg/api/core/v1/models/models.go
  scripts/cli-docs-generate.sh
Labels: bug

#1424 updating installation broken links
  .github/release-drafter.yml
  docs/howtos/development.md
Labels: documentation

#1426 Auth unit tests
  internal/auth/auth.go
  internal/auth/auth_suite_test.go
  internal/auth/auth_test.go
  internal/auth/authfakes/fake_secret_interface.go
  internal/auth/user.go
  internal/cli/admincmd/settings.go
  internal/cli/server/server.go
Labels: chore

#1457 Fix GKE warning about auth plugin
  .github/workflows/gke.yml
Labels: QA

#1440 Test service in EKS scenario
  acceptance/install/scenario4_test.go
Labels: QA

#1443 Fail service unbind if bound to apps and `--unbind` not specified. New option.
  acceptance/api/v1/helpers_test.go
  acceptance/api/v1/namespace_delete_test.go
  acceptance/api/v1/service_bind_test.go
  acceptance/api/v1/service_create_test.go
  acceptance/api/v1/service_delete_test.go
  acceptance/api/v1/service_list_test.go
  acceptance/api/v1/service_show_test.go
  acceptance/api/v1/service_unbind_test.go
  acceptance/api/v1/services_catalog_test.go
  acceptance/apps/rails_test.go
  acceptance/helpers/catalog/misc.go
  acceptance/helpers/machine/machine.go
  acceptance/helpers/machine/services.go
  acceptance/services_test.go
  docs/references/api/swagger.json
  helpers/string.go
  internal/api/v1/docs/configuration.go
  internal/api/v1/docs/service.go
  internal/api/v1/service/bind.go
  internal/api/v1/service/delete.go
  internal/api/v1/service/unbind.go
  internal/api/v1/service/validate.go
  internal/cli/services.go
  internal/cli/usercmd/app_test.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/configuration.go
  internal/cli/usercmd/service.go
  internal/configurations/configurations.go
  internal/manifest/manifest.go
  internal/names/names.go
  internal/names/names_test.go
  internal/services/instances.go
  pkg/api/core/v1/client/services.go
  pkg/api/core/v1/models/models.go
Labels: enhancement

#1470 Fix warning in GKE letsencrypt test
  .github/workflows/gke-letsencrypt.yml
Labels: QA

#1460 ListAll Services endpoint and CatalogService rename
  acceptance/api/v1/services_catalog_test.go
  acceptance/helpers/regex/regex.go
  acceptance/services_test.go
  docs/references/api/swagger.json
  internal/api/v1/docs/service.go
  internal/api/v1/router.go
  internal/api/v1/service/fullindex.go
  internal/api/v1/service/list.go
  internal/auth/auth_test.go
  internal/cli/services.go
  internal/cli/usercmd/app_test.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/service.go
  internal/services/instances.go
  pkg/api/core/v1/client/services.go
Labels: api

#1475 Added APIClient counterfeiter mock
  internal/cli/usercmd/app_test.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
Labels: chore

#1482 Bump actions and golangci-lint (go1.18)
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke.yml
  .golangci.yml
  acceptance/install/scenario4_test.go
Labels: dependencies

#1483 Bump Helm and k8s dependencies
  acceptance/api/v1/application_portforward_test.go
  go.mod
  go.sum
  pkg/api/core/v1/client/apps.go
Labels: dependencies

#1490 Fail fast targeting unauthorized namespaces
  acceptance/api/v1/configurations_mutation_test.go
  acceptance/api/v1/namespace_auth_test.go
  acceptance/api/v1/service_create_test.go
  acceptance/helpers/machine/curl.go
  acceptance/helpers/machine/machine.go
  acceptance/namespaces_test.go
  acceptance/users_test.go
  internal/api/v1/application/controller.go
  internal/api/v1/application/create.go
  internal/api/v1/application/delete.go
  internal/api/v1/application/exec.go
  internal/api/v1/application/index.go
  internal/api/v1/application/logs.go
  internal/api/v1/application/part.go
  internal/api/v1/application/portforward.go
  internal/api/v1/application/restart.go
  internal/api/v1/application/running.go
  internal/api/v1/application/show.go
  internal/api/v1/application/stage.go
  internal/api/v1/application/update.go
  internal/api/v1/auth.go
  internal/api/v1/auth_test.go
  internal/api/v1/configuration/configurationapps.go
  internal/api/v1/configuration/create.go
  internal/api/v1/configuration/delete.go
  internal/api/v1/configuration/index.go
  internal/api/v1/configuration/replace.go
  internal/api/v1/configuration/show.go
  internal/api/v1/configuration/update.go
  internal/api/v1/configurationbinding/create.go
  internal/api/v1/configurationbinding/delete.go
  internal/api/v1/env/index.go
  internal/api/v1/env/match.go
  internal/api/v1/env/set.go
  internal/api/v1/env/show.go
  internal/api/v1/env/unset.go
  internal/api/v1/namespace.go
  internal/api/v1/namespace/delete.go
  internal/api/v1/namespace/show.go
  internal/api/v1/service/controller.go
  internal/api/v1/service/delete.go
  internal/api/v1/service/list.go
  internal/api/v1/service/serviceapps.go
  internal/api/v1/service/show.go
  internal/cli/server/server.go
  internal/cli/usercmd/namespace.go
Labels: api

#1488 Match endpoints for apps and configurations
  .github/workflows/main.yml
  acceptance/api/v1/application_match_test.go
  acceptance/api/v1/configuration_match_test.go
  docs/references/api/swagger.json
  internal/api/v1/application/match.go
  internal/api/v1/configuration/match.go
  internal/api/v1/docs/application.go
  internal/api/v1/docs/configuration.go
  internal/api/v1/docs/service.go
  internal/api/v1/router.go
  internal/cli/usercmd/app.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/configuration.go
  internal/cli/usercmd/service.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/configurations.go
  pkg/api/core/v1/client/services.go
  pkg/api/core/v1/models/app.go
  pkg/api/core/v1/models/models.go
  scripts/collect-coverage.sh
Labels: enhancement, api

#1497 Fix table regex on CLI tests
  acceptance/appcharts_test.go
  acceptance/apps_env_test.go
  acceptance/apps_test.go
  acceptance/bindings_test.go
  acceptance/configurations_test.go
  acceptance/helpers/matchers/matchers.go
  acceptance/helpers/regex/regex.go
  acceptance/namespaces_test.go
  acceptance/services_test.go
  acceptance/settings_test.go
Labels: bug, chore

#1500 Bumped dependencies
  go.mod
  go.sum
Labels: dependencies
