Repository epinio/epinio, pull requests merged in 2022-12, with the labels that each got.

#1922 Collated dependabot changes for dependent modules
  go.mod
  go.sum
Labels: chore

#1921 Collated dependabot changes for CI actions
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/container-image-sample-app.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/release.yml
Labels: devops admin, chore

#1932 Delete namespaces to remove EC2/EBS volumes from AWS
  .github/workflows/eks.yml
Labels: bug, devops admin

#1938 CI Wordpress - Bump tests to PHP 8.0.x.
  acceptance/apps/wordpress_test.go
  acceptance/apps_test.go
Labels: bug, devops admin

#1942 Fix generation of multi-platform images, and signing of the multi-platform manifest
  .goreleaser-qa.yml
  .goreleaser.yml
Labels: bug, security, devops admin

#1962 Deprecated auth method in kubeconfig on GKE
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
Labels: devops admin
