Repository epinio/epinio, pull requests merged in 2022-07, with the labels that each got.

#1598 Update README.md
  README.md
Labels: documentation

#1623 Delete deprecated docs page on how to create a new user
  docs/README.md
  docs/howtos/README.md
  docs/howtos/new-api-user.md
Labels: documentation

#1620 Guard against a missing (nil) response from a websocket dialer problem
  acceptance/install/scenario2_test.go
  pkg/api/core/v1/client/apps.go
Labels: bug

#1643 Fix: mishandling of commit ids in git upload
  acceptance/apps_test.go
  internal/api/v1/application/importgit.go
Labels: bug

#1654 chore: bump cert-manager for dev and CI to 1.8.2.
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke.yml
  .github/workflows/rke.yml
  Makefile
Labels: chore

#1656 fix: missing handling of any kind of leading/trailing space
  acceptance/login_test.go
  internal/cli/usercmd/login.go
Labels: bug, windows

#1661 fix: another mishandling of commit ids. cannot use shallow clone for that case
  internal/api/v1/application/importgit.go
Labels: bug
