Repository epinio/epinio, pull requests merged in 2022-11, with the labels that each got.

#1843 Fix RKE CI trouble
  acceptance/helpers/epinio/epinio.go
  acceptance/helpers/machine/configurations.go
  acceptance/install/scenario3_test.go
Labels: bug

#1841 Fix gke ci upgrade issues
  .github/workflows/gke-upgrade.yml
  acceptance/helpers/catalog/misc.go
  acceptance/helpers/machine/apps.go
  acceptance/helpers/machine/configurations.go
  acceptance/helpers/machine/services.go
  internal/services/instances.go
Labels: bug, testing

#1845 Show cluster internal route to app
  go.sum
  internal/cli/completion.go
  internal/cli/usercmd/app.go
Labels: enhancement

#1851 Fix various service issues
  internal/api/v1/service/create.go
  internal/api/v1/service/delete.go
  internal/helm/helm.go
  pkg/api/core/v1/errors/errors.go
Labels: bug

#1862 Configure EKS EBS CSI driver for k8s 1.23+
  .github/workflows/eks.yml
  scripts/patch-epinio-deployment.sh
Labels: bug

#1881 Fix namespace in app internal routes
  internal/cli/usercmd/app.go
Labels: bug

#1879 Added services' internal routes
  acceptance/services_test.go
  docs/references/api/swagger.json
  internal/cli/usercmd/service.go
  internal/services/instances.go
  internal/services/instances_test.go
  internal/services/servicesfakes/fake_service_interface.go
  internal/services/suite_test.go
  pkg/api/core/v1/models/models.go
Labels: enhancement

#1880 Fix missing help output for root command given a bogus sub command
  internal/cli/root.go
Labels: bug

#1888 CI tweaks to reduce load
  .github/workflows/main.yml
Labels: devops admin, chore
