Repository epinio/epinio, pull requests merged in 2022-03, with the labels that each got.

#1226 Execute release drafter on main branch change
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
Labels: skip-changelog

#1282 Switch release workflows to self-hosted runners
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
Labels: chore

#1289 ApiClient interface
  internal/cli/usercmd/app.go
  internal/cli/usercmd/client.go
  pkg/api/core/v1/client/apps_test.go
  pkg/api/core/v1/client/client.go
  pkg/api/core/v1/client/http.go
  pkg/api/core/v1/client/services.go
Labels: chore

#1291 Moved AppLogs to APIClient
  Makefile
  internal/cli/apps.go
  internal/cli/usercmd/app.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/push.go
  pkg/api/core/v1/client/app_logs_test.go
  pkg/api/core/v1/client/app_restart_test.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/apps_test.go
Labels: chore

#1296 Bump go.mod to 1.17, update modules
  go.mod
  go.sum
Labels: chore

#1297 Namespace cleanup
  acceptance/api/v1/application_create_test.go
  acceptance/api/v1/application_delete_test.go
  acceptance/api/v1/application_deploy_test.go
  acceptance/api/v1/application_importgit_test.go
  acceptance/api/v1/application_index_all_test.go
  acceptance/api/v1/application_index_test.go
  acceptance/api/v1/application_logs_test.go
  acceptance/api/v1/application_portforward_test.go
  acceptance/api/v1/application_restart_test.go
  acceptance/api/v1/application_show_test.go
  acceptance/api/v1/application_stage_test.go
  acceptance/api/v1/application_update_test.go
  acceptance/api/v1/application_upload_test.go
  acceptance/api/v1/configurations_mutation_test.go
  acceptance/api/v1/configurations_test.go
  acceptance/api/v1/orgs_test.go
  acceptance/apps/rails_test.go
  acceptance/apps/wordpress_test.go
  acceptance/apps_env_test.go
  acceptance/apps_test.go
  acceptance/bindings_test.go
  acceptance/configurations_test.go
  acceptance/helpers/machine/apps.go
  acceptance/namespaces_test.go
Labels: chore

#1304 Pin `mc` (Minio CLI) version
  acceptance/api/v1/helpers_test.go
Labels: blocker

#1301 Fix for env variable.
  acceptance/apps_test.go
  internal/cli/apps.go
  internal/cli/push.go
  internal/manifest/manifest.go
Labels: bug, chore

#1317 Fix app chart reference for changed configuration lookup
  internal/helm/helm.go
Labels: bug, blocker

#1318 Bump go developer version to 1.18
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke.yml
  go.mod
  go.sum
Labels: chore
