Repository epinio/epinio, pull requests merged in 2022-06, with the labels that each got.

#1534 Filtered namespaces
  acceptance/api/v1/namespace_auth_test.go
  internal/api/v1/namespace/index.go
  internal/namespaces/namespaces.go
Labels: bug

#1535 Bumped dependencies
  go.mod
  go.sum
Labels: dependencies

#1523 Test - Add workflow to build draft binaries (QA)
  .github/workflows/release-qa.yml
  .goreleaser-qa.yml
Labels: QA

#1543 Removed unnecessary interface
  internal/auth/auth.go
  internal/auth/authfakes/fake_secret_interface.go
Labels: chore

#1555 Fix broken link in release drafter
  .github/release-drafter.yml
Labels: documentation

#1583 fix: path display across platforms.
  helpers/string.go
  internal/cli/admincmd/settings.go
  internal/cli/settings.go
  internal/cli/usercmd/push.go
  pkg/api/core/v1/models/models.go
Labels: bug

#1591 Remove non-existent DEBUG option
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#1593 Tweak trace setup ordering to make `--trace-level` work
  helpers/kubernetes/config/argtoenv.go
  internal/cli/root.go
Labels: bug
