Repository epinio/epinio, pull requests merged in 2023-04, with the labels that each got.

#2151 Fixed status information shown for deployed app with zero instances
  acceptance/apps_test.go
  internal/application/application.go
  internal/application/application_test.go
  internal/cli/usercmd/app.go
  pkg/api/core/v1/models/app.go
Labels: kind/bug, area/ux

#2180 chore: stati -> statuses
  internal/api/v1/application/running.go
  internal/application/application.go
  internal/application/application_test.go
Labels: kind/chore, status/skip-changelog

#2181 Remove deprecated controller.service.name from nginx-ingress
  acceptance/install/scenario4_test.go
  acceptance/install/suite_test.go
Labels: status/devops admin

#2174 fix: missing redeploy of chart from zero instances
  acceptance/apps_test.go
  internal/api/v1/application/update.go
Labels: kind/bug, area/api

#2177 dependabot gh action integration
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/container-image-sample-app.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/upgrade.yml
Labels: kind/chore, kind/dependencies

#2189 Use `golangci-lint` on lint
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  Makefile
  internal/api/v1/application/update.go
Labels: kind/chore, status/skip-changelog

#2190 Dropped application controller
  internal/api/v1/application/controller.go
  internal/api/v1/application/create.go
  internal/api/v1/application/delete.go
  internal/api/v1/application/deploy.go
  internal/api/v1/application/exec.go
  internal/api/v1/application/fullindex.go
  internal/api/v1/application/importgit.go
  internal/api/v1/application/index.go
  internal/api/v1/application/logs.go
  internal/api/v1/application/match.go
  internal/api/v1/application/part.go
  internal/api/v1/application/portforward.go
  internal/api/v1/application/restart.go
  internal/api/v1/application/running.go
  internal/api/v1/application/show.go
  internal/api/v1/application/stage.go
  internal/api/v1/application/update.go
  internal/api/v1/application/upload.go
  internal/api/v1/application/validatecv.go
  internal/api/v1/router.go
Labels: kind/chore, status/skip-changelog

#2202 RKE2 EC2 provisioning
  .github/workflows/rke2-lh-ec2.yml
  README.md
Labels: status/devops admin, kind/chore

#2152 Refactor acceptance tests
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  acceptance/helpers/delete_clusters/delete_clusters.go
  acceptance/helpers/route53/change.go
  acceptance/install/scenario1_test.go
  acceptance/install/scenario2_test.go
  acceptance/install/scenario4_test.go
  acceptance/install/scenario5_test.go
  acceptance/install/scenario6_test.go
Labels: kind/chore, status/skip-changelog

#2198 fix: security, bump docker/docker directly
  go.mod
  go.sum
Labels: kind/bug, area/security

#2207 Disable cache for linter
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/rke2-lh-ec2.yml
Labels: status/devops admin, kind/chore

#2208 Fix workflow dispatch type choice and condition
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
Labels: kind/chore, status/skip-changelog

#2206 Delete ELB for EC2 RKE2 test
  .github/workflows/rke2-lh-ec2.yml
Labels: status/devops admin, kind/chore

#2209 Remove outputs in rke2-lh-ec2 workflow
  .github/workflows/rke2-lh-ec2.yml
Labels: status/devops admin, kind/chore

#2215 Full PATH in KUBECONFIG for GKE CI
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
Labels: status/devops admin, kind/chore

#2217 Added timeouts to setup-go and linting steps
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/rke2-lh-ec2.yml
  .github/workflows/upgrade.yml
Labels: kind/chore

#2216 Added SynchronizedClient tests
  go.mod
  go.sum
  internal/helm/client_test.go
  internal/helm/helm.go
Labels: kind/chore

#2219 fix broken swagger generation
  docs/references/api/swagger.json
  internal/api/v1/docs/docs.go
Labels: kind/bug, status/skip-changelog

#2222 fix: handling of conflicts due to concurrent binding of the same service to multiple apps
  internal/configurations/configurations.go
Labels: kind/bug, area/api

#2226 Added per-release synchronized Helm client
  internal/helm/client.go
  internal/helm/client_test.go
  internal/helm/helm.go
Labels: kind/enhancement

#2229 Fix runners Go version with patch
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/rke2-lh-ec2.yml
  .github/workflows/upgrade.yml
Labels: kind/chore, status/skip-changelog

#2227 Extend `restart` to handle a restaged app
  Makefile
  internal/api/v1/application/restart.go
Labels: kind/bug, area/api

#2232 Skip cache in setup-go and golangci-lint actions
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/rke2-lh-ec2.yml
  .github/workflows/upgrade.yml
Labels: kind/bug, kind/chore, status/skip-changelog

#2233 Update release checklist with Dashboard and UI backend
  .github/ISSUE_TEMPLATE/release_checklist.yaml
Labels: kind/chore, status/skip-changelog

#2221 ADR: extend the application manifest
  .github/workflows/release-sandbox.yml
  docs/decisions/adr-extend-application-manifest.md
Labels: kind/enhancement, area/api

#2240 RKE2 EC2 provisioning: kubeconfig Tag and mode 0644
  .github/workflows/rke2-lh-ec2.yml
Labels: status/devops admin, kind/chore

#2235 fix: missing tab completion for `app env unset`.
  acceptance/appcharts_test.go
  acceptance/apps_env_test.go
  acceptance/apps_test.go
  acceptance/configurations_test.go
  acceptance/namespaces_test.go
  acceptance/services_test.go
  internal/cli/commons.go
  internal/cli/env.go
Labels: kind/bug

#2246 fix: cosign docker images by digest, not tag. avoid a race condition with the latter
  .goreleaser-qa.yml
  .goreleaser.yml
Labels: kind/bug, area/security, status/do not log

#2248 Removed `appchart.Controller`
  internal/api/v1/appchart/controller.go
  internal/api/v1/appchart/index.go
  internal/api/v1/appchart/match.go
  internal/api/v1/appchart/show.go
  internal/api/v1/router.go
Labels: status/skip-changelog, kind/quality

#2251 Add AWS_RKE2 setup deletion
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/rke2-lh-ec2.yml
  acceptance/helpers/delete_clusters/delete_clusters.go
Labels: kind/enhancement, status/devops admin, kind/chore

#2256 Fix workflows and delete clusters to read ssh-key from file
  .github/workflows/delete_clusters.yml
  .github/workflows/rke2-lh-ec2.yml
  acceptance/helpers/delete_clusters/delete_clusters.go
Labels: status/devops admin, kind/chore
