Repository epinio/epinio, pull requests merged in 2023-06, with the labels that each got.

#2362 External registries devel documentation
  docs/howtos/public_external_registry.md
Labels: area/documentation

#2367 Fixed wrong `upgrade responder` configuration
  scripts/upgrade-responder-release-update.sh
Labels: kind/bug, status/skip-changelog

#2369 Fixed passing CI when `codecov` upload fails
  .github/workflows/main.yml
Labels: kind/bug, status/skip-changelog, kind/quality

#2370 Bumped some Go dependencies
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/main.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/rke2-lh-ec2.yml
  .github/workflows/upgrade.yml
  go.mod
  go.sum
  helpers/kubernetes/cluster.go
  internal/api/v1/application/running.go
Labels: kind/chore, kind/dependencies

#2371 Bumped some Github actions
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/cleanup-images.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/rke2-lh-ec2.yml
Labels: kind/dependencies

#2356 Added generic POST/PATCH with tests in configuration API
  pkg/api/core/v1/client/configurations.go
  pkg/api/core/v1/client/configurations_test.go
  pkg/api/core/v1/client/http.go
Labels: status/skip-changelog, kind/quality

#2364 Fixed unexpected waiting during async service deployment
  acceptance/api/v1/service_create_test.go
  internal/helm/helm.go
  internal/services/instances.go
Labels: kind/bug

#2374 chore: units tests for helper/routes.
  helpers/routes/routes.go
  helpers/routes/routes_test.go
  helpers/routes/suite_test.go
Labels: kind/chore, area/chore

#2381 Simplification of DeployApp
  internal/api/v1/application/deploy.go
  internal/api/v1/application/restart.go
  internal/api/v1/application/update.go
  internal/api/v1/configuration/replace.go
  internal/api/v1/configuration/update.go
  internal/api/v1/configurationbinding/create.go
  internal/api/v1/configurationbinding/deletebinding.go
  internal/api/v1/deploy/deploy.go
  internal/api/v1/env/set.go
  internal/api/v1/env/unset.go
Labels: status/skip-changelog, kind/quality

#2386 Centralized API client initialization
  acceptance/services_test.go
  internal/cli/apps.go
  internal/cli/chart.go
  internal/cli/commons.go
  internal/cli/configuration.go
  internal/cli/delete.go
  internal/cli/env.go
  internal/cli/login.go
  internal/cli/namespaces.go
  internal/cli/options.go
  internal/cli/push.go
  internal/cli/root.go
  internal/cli/services.go
  internal/cli/target.go
  internal/cli/usercmd/login.go
Labels: kind/chore, status/skip-changelog

#2383 feat: add new function to get epinio values
  internal/services/instances.go
Labels: safe to test

#2395 Added `--header/-H` flag to CLI
  internal/cli/root.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/client.go
  pkg/api/core/v1/client/http.go
  pkg/api/core/v1/client/http_test.go
Labels: kind/enhancement

#2397 Bumped some Github actions
  .github/workflows/container-image-sample-app.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
Labels: kind/dependencies

#2398 Updated `bci/bci-micro` image
  images/unpacker-Dockerfile
Labels: kind/dependencies

#2400 Updated `bci/bci-micro` image
  images/unpacker-Dockerfile
Labels: kind/dependencies

#2396 Added more generic GET, deleted unneeded ServiceShowRequest
  internal/cli/usercmd/client.go
  internal/cli/usercmd/service.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
  pkg/api/core/v1/client/namespaces.go
  pkg/api/core/v1/client/namespaces_test.go
  pkg/api/core/v1/client/services.go
  pkg/api/core/v1/client/services_test.go
  pkg/api/core/v1/models/models.go
Labels: status/skip-changelog, kind/quality

#2403 Updated `bci/bci-micro` image
  images/unpacker-Dockerfile
Labels: kind/dependencies

#2407 Added Rancher installer script
  Makefile
  scripts/install-rancher.sh
Labels: status/skip-changelog
