Repository epinio/epinio, pull requests merged in 2023-08, with the labels that each got.

#2501 Dependency updates
  .github/workflows/container-image-sample-app.yml
  go.mod
  go.sum
  images/unpacker-Dockerfile
Labels: kind/dependencies

#2502 Better error message for a missing setting.yaml file
  acceptance/settings_test.go
  internal/cli/settings/settings.go
  internal/cli/usercmd/login.go
  pkg/api/core/v1/client/apps_restart_test.go
  pkg/api/core/v1/client/apps_test.go
  pkg/api/core/v1/client/configurations_test.go
  pkg/api/core/v1/client/http.go
  pkg/api/core/v1/client/http_test.go
  pkg/api/core/v1/client/services_test.go
Labels: kind/enhancement

#2503 Added support for Git configurations
  .github/workflows/main.yml
  acceptance/apps_test.go
  helpers/kubernetes/cluster.go
  internal/api/v1/application/importgit.go
  internal/bridge/git/git.go
  internal/bridge/git/git_suite_test.go
  internal/bridge/git/git_test.go
Labels: kind/enhancement

#2457 Added optional `restart` field to `AppUpdate` API
  acceptance/api/v1/application_export_test.go
  acceptance/api/v1/application_update_test.go
  acceptance/api/v1/application_validate_cv_test.go
  acceptance/api/v1/helpers_api_test.go
  acceptance/apps_test.go
  docs/references/api/swagger.json
  internal/api/v1/application/part.go
  internal/api/v1/application/restart.go
  internal/api/v1/application/update.go
  internal/cli/apps.go
  internal/cli/push.go
  internal/cli/usercmd/push.go
  internal/manifest/manifest_test.go
  pkg/api/core/v1/models/app.go
  pkg/api/core/v1/models/models.go
Labels: kind/bug

#2505 Fixed wrong merge
  internal/cli/usercmd/push.go
Labels: kind/bug, status/skip-changelog

#2506 Removed Kubernetes API access from `settings update-ca` command
  acceptance/services_test.go
  acceptance/settings_test.go
  acceptance/testenv/env.go
  internal/cli/admincmd/settings.go
Labels: kind/chore

#2514 fix disk request handling with a default of last resort.
  internal/api/v1/application/stage.go
Labels: kind/bug, status/skip-changelog

#2512 Enabled redirection of trace output to arbitrary file
  helpers/tracelog/logger.go
  internal/cli/server.go
Labels: kind/enhancement

#2513 Show service credentials in detail view
  acceptance/configurations_test.go
  acceptance/services_test.go
  docs/references/api/swagger.json
  internal/api/v1/service/create.go
  internal/api/v1/service/show.go
  internal/cli/usercmd/configuration.go
  internal/cli/usercmd/service.go
  internal/helm/helm.go
  internal/services/instances.go
  pkg/api/core/v1/models/models.go
Labels: kind/enhancement

#2511 fix storage of service custom value settings to roundtrip cleanly
  acceptance/services_test.go
  internal/services/instances.go
Labels: kind/bug, area/api

#2520 fixed goreleaser deprecations
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .goreleaser-qa.yml
  .goreleaser.yml
Labels: kind/chore

#2517 fixed mishanding of export jobs on cancellation, and for multiple concurrent requests
  internal/api/v1/application/part.go
Labels: kind/bug, area/ux, area/api
