Repository epinio/epinio, pull requests merged in 2023-01, with the labels that each got.

#1984 Add helm to macos-12 runner
  .github/workflows/eks.yml
Labels: devops admin

#1985 New flow for container cleanup
  .github/workflows/cleanup-images.yml
Labels: chore

#1986 fixup: permissions
  .github/workflows/cleanup-images.yml
Labels: kind/chore

#1990 image cleanup - Fix: daily cron, not just 1st of month
  .github/workflows/cleanup-images.yml
Labels: kind/bug

#1991 Go modules update
  go.mod
  go.sum
Labels: kind/chore, kind/dependencies, area/chore

#1993 bump drafter config to use changed labels
  .github/release-drafter.yml
Labels: kind/chore, area/chore

#1994 image cleanup - separate step to remove old untagged images
  .github/workflows/cleanup-images.yml
Labels: kind/chore, area/chore

#1998 Remove Ginkgo deprecated flag
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/eks-test.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-test.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/main.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/upgrade.yml
  Makefile
Labels: area/chore

#2001 Bumping k3s image to v1.25.4-k3s1 for ci tests
  scripts/acceptance-cluster-setup.sh
Labels: kind/chore

#2008 bring back image k3s:v1.20.11-k3s2 for ci tests
  scripts/acceptance-cluster-setup.sh
Labels: area/chore

#2016 chore: debug support, manual trigger
  .github/workflows/release.yml
Labels: kind/chore

#2015 trial: copy permissions back into the job
  .github/workflows/release.yml
Labels: kind/bug, area/security

#2010 Update Release Checklist template
  .github/ISSUE_TEMPLATE/release_checklist.yaml
Labels: status/devops admin, area/QA

#2030 Added ADRs
  docs/decisions/README.md
  docs/decisions/adr-template.md
Labels: kind/chore

#2026 Bot module assessment
  go.mod
  go.sum
Labels: kind/chore

#2027 Bot image assessment
  images/unpacker-Dockerfile
Labels: kind/chore

#2028 Bot action assessment
  .github/workflows/container-image-sample-app.yml
Labels: kind/chore

#2032 Update release_checklist.yaml
  .github/ISSUE_TEMPLATE/release_checklist.yaml
Labels: kind/chore

#2034 Fixed reuse of the existing Release draft
  .goreleaser.yml
Labels: kind/bug

#2033 Fixed Epinio Tap (homebrew)
  .github/workflows/release-publish.yml
  .goreleaser.yml
Labels: kind/bug

#2047 Fix port forwarding for newer kube versions
  internal/api/v1/application/exec.go
  internal/api/v1/application/portforward.go
  internal/api/v1/application/proxy.go
  internal/auth/certs.go
  internal/cli/settings/settings.go
  scripts/acceptance-cluster-setup.sh
Labels: kind/bug, area/api

#2048 Automate upgrade responder config
  .github/workflows/release-publish.yml
  .github/workflows/release-sandbox.yml
  scripts/cognito-login.sh
  scripts/upgrade-responder-release-update.sh
Labels: kind/chore

#2050 Fix app export for Rancher integration (chart is asset file, not url).
  internal/api/v1/application/part.go
Labels: kind/bug, area/api
