Repository epinio/epinio, pull requests merged in 2023-07, with the labels that each got.

#2408 Added generic Configuration delete
  acceptance/appcharts_test.go
  acceptance/apps_test.go
  acceptance/configurations_test.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/configuration.go
  internal/cli/usercmd/push.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
  pkg/api/core/v1/client/configurations.go
  pkg/api/core/v1/client/configurations_test.go
  pkg/api/core/v1/client/http.go
Labels: status/skip-changelog, kind/quality

#2421 CI Remove Settings key if not present in existing service CRD
  acceptance/helpers/catalog/misc.go
  acceptance/install/suite_test.go
Labels: status/devops admin

#2426 Added generic Service delete
  internal/cli/usercmd/client.go
  internal/cli/usercmd/service.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
  pkg/api/core/v1/client/configurations_test.go
  pkg/api/core/v1/client/http.go
  pkg/api/core/v1/client/services.go
  pkg/api/core/v1/client/services_test.go
Labels: status/skip-changelog, kind/quality

#2423 Added proper status check for Service deployments
  acceptance/configurations_test.go
  acceptance/helpers/catalog/misc.go
  acceptance/helpers/machine/services.go
  acceptance/services_test.go
  internal/helm/client.go
  internal/helm/helm.go
  internal/services/instances.go
  pkg/api/core/v1/models/models.go
Labels: kind/bug

#2422 Update release_checklist.yaml
  .github/ISSUE_TEMPLATE/release_checklist.yaml
Labels: kind/chore, status/skip-changelog

#2424 Fixed service deploy issues due to expired auth token in the helm packages
  internal/helm/helm.go
Labels: kind/bug

#2434 Skip cleanup for non-scheduled run
  .github/workflows/clientsync.yml
  .github/workflows/main.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/rke2-lh-ec2.yml
  .github/workflows/upgrade-bound.yml
  .github/workflows/upgrade.yml
Labels: kind/chore, status/skip-changelog

#2433 Fixed missing custom headers in login
  internal/cli/root.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/login.go
  internal/cli/usercmd/login_oidc.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
  pkg/api/core/v1/client/client.go
Labels: kind/bug, status/skip-changelog

#2439 Changed test service from mysql to postgresql
  acceptance/apps_test.go
  acceptance/configurations_test.go
  acceptance/helpers/matchers/matchers.go
  acceptance/services_test.go
Labels: kind/chore, status/skip-changelog

#2435 Moved retry for `StagingComplete` and `AppRunning`
  helpers/error.go
  internal/cli/usercmd/app.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/push.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/apps_restart_test.go
  pkg/api/core/v1/client/apps_test.go
Labels: status/skip-changelog, kind/quality

#2438 Updated github action dependencies
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/rke2-lh-ec2.yml
Labels: kind/dependencies

#2437 Updated image dependences
  images/unpacker-Dockerfile
Labels: kind/dependencies

#2436 Updated go modules dependencies
  go.mod
  go.sum
Labels: kind/dependencies

#2442 Removed old http `do` func
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/http.go
  pkg/api/core/v1/client/http_test.go
Labels: status/skip-changelog, kind/quality

#2446 Add region flag for eksctl-0.148.0 workaround
  .github/workflows/eks.yml
Labels: status/devops admin, area/QA

#2447 Added error check for release deletion
  internal/helm/helm.go
  internal/services/instances.go
Labels: kind/bug

#2449 ci: add automation to generate README.md for tests
  .github/workflows/update-tests-description.yaml
  Makefile
  scripts/generate-readme
  scripts/generate-tests-description
Labels: area/QA

#2448 Updated README
  README.md
Labels: area/documentation, kind/enhancement

#2454 small cleanup of API helpers
  acceptance/api/v1/application_create_test.go
  acceptance/api/v1/application_deploy_test.go
  acceptance/api/v1/application_show_test.go
  acceptance/api/v1/application_stage_test.go
  acceptance/api/v1/application_update_test.go
  acceptance/api/v1/helpers_api_test.go
  acceptance/api/v1/helpers_test.go
Labels: kind/chore, status/skip-changelog

#2456 Update API refactor
  internal/api/v1/application/update.go
  internal/api/v1/deploy/deploy.go
  pkg/api/core/v1/models/app.go
Labels: kind/chore, status/skip-changelog

#2460 Fixed wrong client initialization
  internal/cli/clientsync.go
  internal/cli/clientsync_test.go
  internal/cli/info.go
  internal/cli/info_test.go
  internal/cli/root.go
Labels: kind/bug

#2461 Refactor of HTTP client with handlers, and AppGetPart
  internal/api/v1/application/part.go
  internal/cli/usercmd/app.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/http.go
  pkg/api/core/v1/models/models.go
Labels: status/skip-changelog, kind/quality

#2459 Show custom values for service instances
  acceptance/services_test.go
  docs/references/api/swagger.json
  internal/cli/usercmd/service.go
  internal/helm/helm.go
  internal/services/instances.go
  pkg/api/core/v1/models/models.go
Labels: kind/enhancement, kind/goobe

#2462 Remove `upload` httpclient duplication
  internal/cli/usercmd/client.go
  internal/cli/usercmd/push.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/apps_test.go
  pkg/api/core/v1/client/http.go
Labels: status/skip-changelog, kind/quality

#2463 Removed `AppImportGit` client duplication
  internal/cli/usercmd/client.go
  internal/cli/usercmd/push.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/apps_test.go
  pkg/api/core/v1/client/http.go
Labels: status/skip-changelog, kind/quality

#2474 Fixed number of retry during service creation
  internal/helm/helm.go
Labels: kind/bug

#2473 Added git URL and git provider validation
  acceptance/api/v1/application_deploy_test.go
  acceptance/api/v1/helpers_api_test.go
  acceptance/api/v1/helpers_test.go
  acceptance/apps_test.go
  internal/api/v1/application/deploy.go
  internal/cli/usercmd/push.go
  pkg/api/core/v1/models/app.go
  pkg/api/core/v1/models/app_test.go
Labels: kind/bug

#2482 drop old mount paths for service-based configurations
  internal/api/v1/deploy/deploy.go
  internal/cli/usercmd/configuration.go
Labels: kind/chore

#2479 remove remaining support for helmcontroller-based services
  docs/references/api/swagger.json
  internal/cli/usercmd/service.go
  internal/services/instances.go
  pkg/api/core/v1/models/models.go
Labels: kind/chore

#2486 Fixed failure to abort port-forwarding early when targeted service does not exist
  acceptance/services_test.go
  internal/cli/usercmd/service.go
Labels: kind/bug

#2492 Removed unused `errors` package
  internal/errors/errors.go
Labels: kind/chore, status/skip-changelog

#2487 Add branch and revision to ImportGit API
  acceptance/api/v1/application_importgit_test.go
  acceptance/api/v1/helpers_api_test.go
  docs/references/api/swagger.json
  go.mod
  go.sum
  internal/api/v1/application/importgit.go
  internal/cli/usercmd/push.go
  pkg/api/core/v1/models/models.go
Labels: kind/enhancement

#2485 Support array index syntax and deeper object nesting for custom values of services.
  acceptance/helpers/catalog/misc.go
  acceptance/services_test.go
  internal/application/application.go
  internal/cli/usercmd/settings.go
  internal/services/instances.go
Labels: kind/enhancement
