Repository epinio/epinio, pull requests merged in 2023-05, with the labels that each got.

#2258 Fix "KUBECONFIG" env var quoting for AKS*-CI (Windows)
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
Labels: status/devops admin, kind/chore

#2204 Added logging ADR
  docs/decisions/20230414-logging.md
Labels: area/documentation

#2270 Fixed Docker rate limiting
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/container-images.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/unpacker-image.yml
Labels: kind/bug, status/skip-changelog

#2249 Fixed same suggestions for multiple resources
  acceptance/apps_test.go
  acceptance/configurations_test.go
  acceptance/services_test.go
  internal/cli/commons.go
  internal/cli/configuration.go
  internal/cli/delete.go
  internal/cli/env.go
  internal/cli/options.go
  internal/cli/services.go
  internal/cli/usercmd/configuration.go
Labels: kind/bug

#2272 Revert "Fixed Docker rate limiting"
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/container-images.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
Labels: kind/bug, status/skip-changelog

#2268 Dependabot update
  .github/workflows/cleanup-images.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  go.mod
  go.sum
  images/unpacker-Dockerfile
Labels: kind/dependencies

#2279 Chore: Removed env controller structure
  internal/api/v1/env/controller.go
  internal/api/v1/env/index.go
  internal/api/v1/env/match.go
  internal/api/v1/env/set.go
  internal/api/v1/env/show.go
  internal/api/v1/env/unset.go
  internal/api/v1/router.go
Labels: status/skip-changelog, kind/quality

#2269 Updated to Go version 1.20.4
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/rke2-lh-ec2.yml
  .github/workflows/upgrade.yml
  .golangci.yml
  go.mod
Labels: kind/dependencies

#2278 Chore: Removed namespace controller structure
  internal/api/v1/namespace/controller.go
  internal/api/v1/namespace/create.go
  internal/api/v1/namespace/delete.go
  internal/api/v1/namespace/index.go
  internal/api/v1/namespace/match.go
  internal/api/v1/namespace/show.go
  internal/api/v1/router.go
Labels: status/skip-changelog, kind/quality

#2255 Removed `configuration.Controller`
  internal/api/v1/configuration/configurationapps.go
  internal/api/v1/configuration/controller.go
  internal/api/v1/configuration/create.go
  internal/api/v1/configuration/delete.go
  internal/api/v1/configuration/fullindex.go
  internal/api/v1/configuration/index.go
  internal/api/v1/configuration/match.go
  internal/api/v1/configuration/replace.go
  internal/api/v1/configuration/show.go
  internal/api/v1/configuration/update.go
  internal/api/v1/router.go
Labels: kind/chore, status/skip-changelog, kind/quality

#2282 Chore: Removed configuration binding controller structure
  internal/api/v1/configurationbinding/controller.go
  internal/api/v1/configurationbinding/create.go
  internal/api/v1/configurationbinding/delete.go
  internal/api/v1/router.go
Labels: kind/chore, status/skip-changelog, kind/quality

#2287 Release CI: Extended the set of artifacts to generate SBOMs for.
  .goreleaser-qa.yml
  .goreleaser.yml
Labels: area/security, kind/chore, status/skip-changelog

#2293 Fix CI application-cli-apps stuckup
  acceptance/apps_test.go
Labels: kind/bug, kind/chore, area/QA, status/skip-changelog

#2300 Fix mishandling of --all when no resources are found/available.
  internal/cli/usercmd/app.go
  internal/cli/usercmd/configuration.go
  internal/cli/usercmd/namespace.go
  internal/cli/usercmd/service.go
Labels: kind/bug

#2298 Validate git provider strings, client and server
  acceptance/api/v1/application_deploy_test.go
  acceptance/api/v1/helpers_test.go
  acceptance/apps_test.go
  docs/references/api/swagger.json
  internal/api/v1/application/deploy.go
  internal/application/origin.go
  internal/cli/push.go
  internal/manifest/manifest.go
  pkg/api/core/v1/models/app.go
Labels: kind/bug, status/skip-changelog

#2301 fixed transfer of bad namespace information on login (to new cluster)
  acceptance/helpers_test.go
  acceptance/login_test.go
  internal/cli/usercmd/login.go
Labels: kind/bug

#2309 auto-completion for --git-provider and --app-chart
  internal/cli/apps.go
  internal/cli/push.go
  pkg/api/core/v1/models/app.go
Labels: kind/enhancement, status/skip-changelog

#2310 unit tests to extend coverage in models
  acceptance/info_test.go
  pkg/api/core/v1/models/env.go
  pkg/api/core/v1/models/models_test.go
  pkg/api/core/v1/models/suite_test.go
Labels: status/skip-changelog, area/chore, kind/quality

#2312 fix: mishandling of checks and settings, when starting from no settings at all
  internal/cli/usercmd/login.go
Labels: kind/bug, status/skip-changelog

#2313 Moved test coverage upload at the end of tests
  .github/workflows/main.yml
Labels: kind/bug, kind/quality

#2304 Moved exec helper
  acceptance/api/v1/service_bind_test.go
  acceptance/helpers/catalog/misc.go
  acceptance/helpers/exec.go
  helpers/exec.go
Labels: status/skip-changelog, kind/quality

#2321 Added unit tests to `epinio info` command
  helpers/termui/ui.go
  internal/cli/docs/generate-cli-docs.go
  internal/cli/info.go
  internal/cli/info_test.go
  internal/cli/root.go
  internal/cli/usercmd/client.go
Labels: status/skip-changelog, kind/quality

#2323 PR 'kind/dependencies' should do a patch version bump
  .github/release-drafter.yml
Labels: status/skip-changelog, area/chore

#2324 More cleanup of unused code, plus tests
  acceptance/apps_test.go
  internal/application/application.go
  internal/auth/user.go
  internal/configurations/configurations.go
  internal/registry/registry.go
  internal/s3manager/s3manager.go
Labels: status/skip-changelog, area/chore

#2330 Target workspace namespace for EKS/EC2 tests
  acceptance/install/scenario4_test.go
Labels: status/devops admin, kind/chore

#2334 Implementation of new go 1.20 cover feature
  .github/workflows/main.yml
  Makefile
  acceptance/testenv/epinio.go
  internal/cli/server.go
  main_test.go
  scripts/collect-coverage.sh
  scripts/patch-epinio-deployment.sh
  scripts/prepare-environment-k3d.sh
Labels: kind/quality

#2319 restart after restage, except if app not active, or disabled by user (new option)
  acceptance/apps_test.go
  internal/cli/apps.go
  internal/cli/usercmd/app.go
  internal/cli/usercmd/app_test.go
Labels: kind/enhancement

#2325 Added unit tests to `epinio client-sync` command
  internal/cli/clientsync.go
  internal/cli/clientsync_test.go
  internal/cli/root.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/clientsync.go
  internal/selfupdater/selfupdater.go
  internal/selfupdater/selfupdaterfakes/fake_updater.go
Labels: status/skip-changelog, area/chore

#2289 New logout command
  acceptance/logout_test.go
  internal/cli/login.go
  internal/cli/root.go
  internal/cli/usercmd/logout.go
Labels: kind/enhancement

#2350 Fix for cosign 2.0.0+
  .goreleaser-qa.yml
  .goreleaser.yml
Labels: kind/bug, kind/dependencies, status/skip-changelog

#2351 Fixed cosign verification
  .github/workflows/release.yml
Labels: kind/bug, status/skip-changelog

#2348 Added CA certs in validation
  go.mod
  go.sum
  helpers/cahash/cahash.go
  helpers/cahash/cahash_test.go
  helpers/cahash/suite_test.go
Labels: kind/bug

#2353 Update release-drafter.yml for prereleases
  .github/release-drafter.yml
Labels: kind/chore, status/skip-changelog
