Repository epinio/epinio, pull requests merged in 2023-02, with the labels that each got.

#2070 Fixed release workflow, checklist and minor
  .github/ISSUE_TEMPLATE/release_checklist.yaml
  .github/workflows/release-publish.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  README.md
Labels: kind/bug, area/chore

#2071 fix: missing body information for service/configuration batch delete endpoints
  docs/references/api/swagger.json
  internal/api/v1/docs/configuration.go
  internal/api/v1/docs/service.go
Labels: kind/bug, area/documentation

#2073 Bump helm.sh to 3.11.0, this also gives us containerd 0.6.15
  go.mod
  go.sum
Labels: area/security, kind/dependencies

#2066 Dependabot module updates
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/eks-test.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-test.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/main.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/upgrade.yml
  go.mod
  go.sum
Labels: kind/chore

#2065 Dependabot action updates
  .github/workflows/container-images.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/unpacker-image.yml
Labels: kind/chore

#2063 chore: bump Go version in workflows
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks-test.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-test.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/upgrade.yml
  .golangci.yml
  go.mod
Labels: kind/chore, area/QA

#2077 Fix loss of certs trusted without user intervention from local settings
  internal/cli/usercmd/login.go
Labels: kind/bug, area/security, area/ux

#2078 Fix and refactor various command completions
  internal/cli/apps.go
  internal/cli/commons.go
  internal/cli/configuration.go
Labels: kind/bug, area/ux

#2079 Added CIVO marketplace automation
  .github/ISSUE_TEMPLATE/release_checklist.yaml
  .github/workflows/release-publish.yml
Labels: area/chore

#2081 Provide app namespace in file written by `app manifest`
  acceptance/apps_test.go
  internal/cli/usercmd/app.go
  pkg/api/core/v1/models/models.go
Labels: kind/enhancement

#2091 EKS-CI 1.24+ workarounds
  acceptance/install/scenario4_test.go
  scripts/eks-cri-allow-http-registries.yaml
Labels: status/devops admin

#2098 Update release_checklist.yaml
  .github/ISSUE_TEMPLATE/release_checklist.yaml
Labels: kind/chore

#2103 Fixed missing release notes
  .github/workflows/release.yml
Labels: kind/chore

#2112 Write template for epics
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/release_checklist.yaml
Labels: kind/enhancement, kind/chore, area/chore
