Repository epinio/epinio, pull requests merged in 2023-09, with the labels that each got.

#2531 Added `https` fallback to login
  internal/cli/login.go
Labels: kind/enhancement

#2533 Moved some CLI commands to `cmd` package
  internal/cli/cmd/clientsync.go
  internal/cli/cmd/clientsync_test.go
  internal/cli/cmd/info.go
  internal/cli/cmd/info_test.go
  internal/cli/cmd/suite_test.go
  internal/cli/root.go
  internal/cli/usercmd/app_test.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/login.go
Labels: kind/chore, status/skip-changelog

#2546 Moved `termui` package
  helpers/kubernetes/cluster.go
  internal/cli/logprinter/logprinter.go
  internal/cli/root.go
  internal/cli/server.go
  internal/cli/termui/dot_progress.go
  internal/cli/termui/spin_progress.go
  internal/cli/termui/tables.go
  internal/cli/termui/ui.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/login.go
  internal/cli/usercmd/push.go
  pkg/api/core/v1/client/http.go
Labels: kind/chore, status/skip-changelog

#2547 Add `--output` flag with JSON support for Epinio namespace list and show commands
  acceptance/namespaces_test.go
  internal/cli/commons.go
  internal/cli/enum_flag.go
  internal/cli/namespaces.go
  internal/cli/root.go
  internal/cli/termui/ui.go
  internal/cli/usercmd/namespace.go
Labels: kind/enhancement

#2554 fix missing mapping from service to secret name in service replace API
  internal/services/instances.go
Labels: kind/bug, area/api, status/skip-changelog

#2553 Updated release checklists
  .github/ISSUE_TEMPLATE/release_candidate_checklist.yaml
  .github/ISSUE_TEMPLATE/release_checklist.yaml
Labels: kind/chore, status/skip-changelog

#2557 Moved `login` and `logout` cmd to `cmd` package
  internal/cli/cmd/cmdfakes/fake_login_service.go
  internal/cli/cmd/login.go
  internal/cli/cmd/login_test.go
  internal/cli/login.go
  internal/cli/root.go
Labels: status/skip-changelog, area/chore

#2562 Added support for --output json to configuration list and show
  acceptance/configurations_test.go
  internal/cli/cmd/args.go
  internal/cli/cmd/cmdfakes/fake_configuration_app_matcher.go
  internal/cli/cmd/cmdfakes/fake_configuration_matcher.go
  internal/cli/cmd/cmdfakes/fake_configuration_service.go
  internal/cli/cmd/configurations.go
  internal/cli/cmd/configurations_test.go
  internal/cli/cmd/flags.go
  internal/cli/commons.go
  internal/cli/configuration.go
  internal/cli/delete.go
  internal/cli/root.go
  internal/cli/services.go
  internal/cli/termui/ui.go
  internal/cli/usercmd/configuration.go
  internal/cli/usercmd/namespace.go
Labels: kind/enhancement

#2567 Added `GORELEASER_CURRENT_TAG` var for release
  .github/workflows/release.yml
Labels: kind/bug, status/skip-changelog

#2566 Fixed a mishandling of apps in `delete --unbind`
  acceptance/services_test.go
  internal/api/v1/service/bind.go
  internal/api/v1/service/delete.go
  internal/api/v1/service/unbind.go
Labels: kind/bug, area/api

#2509 added export to registries
  acceptance/apps_test.go
  docs/references/api/swagger.json
  helpers/kubernetes/cluster.go
  internal/api/v1/application/export.go
  internal/api/v1/application/part.go
  internal/api/v1/docs/application.go
  internal/api/v1/docs/exportregistry.go
  internal/api/v1/exportregistry/index.go
  internal/api/v1/exportregistry/match.go
  internal/api/v1/router.go
  internal/cli/apps.go
  internal/cli/commons.go
  internal/cli/exportregistry.go
  internal/cli/root.go
  internal/cli/usercmd/app.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/exportregistry.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
  internal/helm/client.go
  internal/helm/helm.go
  internal/registry/registry.go
  pkg/api/core/v1/client/apps.go
  pkg/api/core/v1/client/exportregistry.go
  pkg/api/core/v1/models/models.go
Labels: kind/enhancement

#2597 Fix codeblock format issue and refresh language.
  README.md
Labels: area/documentation

#2585 Typo fixed
  .github/ISSUE_TEMPLATE/release_candidate_checklist.yaml
Labels: kind/chore

#2592 chore: remove linkerd from CI and other build files
  .github/workflows/container-images.yml
  images/linkerd-Dockerfile
Labels: kind/chore, status/skip-changelog, area/chore

#2593 chore: remove unused release-qa workflow
  .github/workflows/release-qa.yml
Labels: kind/chore, status/skip-changelog

#2576 action updates
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/cleanup-images.yml
  .github/workflows/container-image-sample-app.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/rke2-lh-ec2.yml
Labels: kind/dependencies, area/chore

#2577 Bump go module dependencies
  go.mod
  go.sum
Labels: kind/dependencies, area/chore

#2575 Bump bci/bci-micro from 15.5.11.2 to 15.5.11.3 in /images
  images/unpacker-Dockerfile
Labels: kind/dependencies, area/chore

#2616 chore: bump goreleaser to 1.20.0 (note: 1.21.x looks too hot)
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
Labels: kind/chore, status/skip-changelog

#2615 chore: bump ginkgo framework to 2.11.0
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/main.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/rke2-lh-ec2.yml
  .github/workflows/upgrade-bound.yml
  .github/workflows/upgrade.yml
Labels: kind/chore, status/skip-changelog

#2618 Update nginx-ingress helm flag for `setAsDefaultIngress=true` in CI
  acceptance/install/suite_test.go
Labels: status/devops admin
