Repository epinio/epinio, pull requests merged in 2023-10, with the labels that each got.

#2550 Added `gitproxy` endpoint
  acceptance/api/v1/gitproxy_test.go
  acceptance/api/v1/helpers_api_test.go
  helpers/cahash/cahash.go
  internal/api/v1/auth_test.go
  internal/api/v1/gitproxy/gitproxy.go
  internal/api/v1/gitproxy/gitproxy_test.go
  internal/api/v1/gitproxy/suite_test.go
  internal/api/v1/router.go
  pkg/api/core/v1/models/gitproxy.go
Labels: kind/enhancement

#2620 Switch to ingress-nginx from kubernetes.io in CI
  acceptance/helpers/delete_clusters/delete_clusters.go
  acceptance/install/scenario4_test.go
  acceptance/install/suite_test.go
Labels: status/devops admin

#2622 Fixed `app export` on multinode clusters with RWO storage
  internal/api/v1/application/export.go
  internal/api/v1/application/part.go
Labels: kind/bug

#2588 Cache app charts in the server pod
  internal/api/v1/application/export.go
  internal/api/v1/application/part.go
  internal/cli/settings/settings.go
  internal/helm/helm.go
  internal/manifest/manifest.go
  internal/urlcache/suite_test.go
  internal/urlcache/urlcache.go
  internal/urlcache/urlcache_test.go
  scripts/appchart.sh
Labels: kind/enhancement, area/api

#2604 Extended info API endpoint with dex availability flag, and made accessible without authentication
  acceptance/info_test.go
  acceptance/users_test.go
  docs/references/api/swagger.json
  internal/api/v1/info.go
  internal/api/v1/router.go
  internal/cli/cmd/info_test.go
  internal/cli/server/server.go
  internal/cli/usercmd/info.go
  pkg/api/core/v1/client/info.go
  pkg/api/core/v1/models/models.go
Labels: kind/enhancement, area/api

#2617 Fixed mishandling of scheme prefixes in route specifications
  acceptance/apps_test.go
  internal/api/v1/application/create.go
  internal/api/v1/application/update.go
Labels: kind/bug, area/api

#2626 Keep images built for CI separate from release images by way of tagging
  .github/workflows/cleanup-images.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/upgrade-bound.yml
  .github/workflows/upgrade.yml
  scripts/build-images.sh
  scripts/prepare-environment-k3d.sh
Labels: kind/bug, area/QA, status/skip-changelog

#2633 Moved middlewares to `middleware` package
  internal/api/v1/middleware/auth.go
  internal/api/v1/middleware/auth_test.go
  internal/api/v1/middleware/authentication.go
  internal/api/v1/middleware/middleware.go
  internal/api/v1/middleware/namespace.go
  internal/api/v1/middleware/suite_test.go
  internal/api/v1/middleware/token.go
  internal/auth/auth.go
  internal/auth/user.go
  internal/cli/server/server.go
Labels: kind/chore

#2634 Added `--output json` support to the `epinio service list|show` commands.
  acceptance/services_test.go
  internal/cli/cmd/args.go
  internal/cli/cmd/cmdfakes/fake_catalog_matcher.go
  internal/cli/cmd/cmdfakes/fake_service_app_matcher.go
  internal/cli/cmd/cmdfakes/fake_service_chart_value_matcher.go
  internal/cli/cmd/cmdfakes/fake_service_matcher.go
  internal/cli/cmd/cmdfakes/fake_services_service.go
  internal/cli/cmd/services.go
  internal/cli/cmd/services_test.go
  internal/cli/commons.go
  internal/cli/root.go
  internal/cli/services.go
  internal/cli/usercmd/service.go
Labels: kind/enhancement

#2640 Added logger to AuthService
  internal/api/v1/gitconfig/create.go
  internal/api/v1/gitconfig/delete.go
  internal/api/v1/middleware/authentication.go
  internal/api/v1/middleware/token.go
  internal/api/v1/namespace/create.go
  internal/api/v1/namespace/delete.go
  internal/auth/auth.go
  internal/auth/user.go
Labels: kind/chore

#2636 Added --output json support to the epinio app list|show commands
  acceptance/apps_test.go
  internal/cli/apps.go
  internal/cli/chart.go
  internal/cli/cmd/appchart.go
  internal/cli/cmd/appenv.go
  internal/cli/cmd/apps.go
  internal/cli/cmd/apps_test.go
  internal/cli/cmd/args.go
  internal/cli/cmd/cmdfakes/fake_app_chart_matcher.go
  internal/cli/cmd/cmdfakes/fake_app_matcher.go
  internal/cli/cmd/cmdfakes/fake_app_var_matcher.go
  internal/cli/cmd/cmdfakes/fake_appcharts_service.go
  internal/cli/cmd/cmdfakes/fake_appenv_service.go
  internal/cli/cmd/cmdfakes/fake_applications_service.go
  internal/cli/cmd/cmdfakes/fake_registry_matcher.go
  internal/cli/commons.go
  internal/cli/delete.go
  internal/cli/env.go
  internal/cli/gitconfigs.go
  internal/cli/options.go
  internal/cli/push.go
  internal/cli/root.go
  internal/cli/usercmd/app.go
  internal/cli/usercmd/push.go
Labels: kind/enhancement

#2648 Added `/me` endpoint to check credentials
  acceptance/api/v1/helpers_api_test.go
  acceptance/api/v1/me_test.go
  internal/api/v1/me.go
  internal/cli/server/server.go
  internal/cli/usercmd/client.go
  internal/cli/usercmd/login.go
  internal/cli/usercmd/usercmdfakes/fake_apiclient.go
  pkg/api/core/v1/client/http.go
  pkg/api/core/v1/client/info.go
  pkg/api/core/v1/models/models.go
Labels: kind/enhancement

#2654 Added backward compatible credentials check for Epinio versions up to `<v1.10.0`
  internal/cli/usercmd/login.go
Labels: kind/bug, kind/chore, status/skip-changelog

#2655 dependencies - go module bumps, and action update
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/rke2-lh-ec2.yml
  go.mod
  go.sum
Labels: kind/chore, kind/dependencies

#2647 Adding test for critical endpoints over different k8s versions
  .github/workflows/main.yml
  Makefile
  scripts/acceptance-cluster-setup-several-k8s-versions.sh
Labels: area/QA

#2660 Update user roles on each new login session
  internal/api/v1/gitconfig/create.go
  internal/api/v1/middleware/authentication.go
  internal/api/v1/namespace/create.go
  internal/auth/auth.go
  internal/auth/auth_test.go
  internal/auth/user.go
Labels: kind/bug

#2657 Wait until certificateRequests are Ready in LE tests
  acceptance/install/scenario2_test.go
  acceptance/install/scenario5_test.go
Labels: status/devops admin

#2661 Removing clean all job between older / latest k8s versions on cep test
  .github/workflows/main.yml
Labels: area/QA

#2675 Removed deprecated `rand.Seed`
  acceptance/apps_test.go
  acceptance/login_test.go
  acceptance/services_test.go
  acceptance/suite_test.go
  internal/application/application_test.go
  internal/auth/auth_test.go
  internal/bridge/git/git_test.go
  internal/services/instances_test.go
Labels: kind/chore, status/skip-changelog

#2676 Added ConfigMapInterface to AuthService
  internal/auth/auth.go
  internal/auth/auth_test.go
  internal/auth/authfakes/fake_config_map_interface.go
Labels: kind/chore, status/skip-changelog

#2679 Update traefik values for CI
  acceptance/install/suite_test.go
Labels: status/devops admin

#2683 Procfile for golang-sample-app needed for upgrade tests
  acceptance/install/suite_test.go
Labels: status/devops admin, area/QA
