Repository epinio/epinio, pull requests merged in 2023-03, with the labels that each got.

#2121 Chore: disable version tracking/reporting in the scenario CI flows.
  .github/workflows/rke-upgrade.yml
  acceptance/helpers/epinio/epinio.go
  acceptance/install/scenario1_test.go
  acceptance/install/scenario2_test.go
  acceptance/install/scenario3_test.go
  acceptance/install/scenario4_test.go
  acceptance/install/scenario5_test.go
  acceptance/install/scenario6_test.go
Labels: kind/chore, area/QA

#2125 Bot modules update
  go.mod
  go.sum
Labels: area/chore

#2124 Bot actions update
  .github/workflows/cleanup-images.yml
Labels: area/chore

#2128 Fix Go version
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks-test.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-test.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/upgrade.yml
Labels: kind/chore, area/chore

#2127 Update release_checklist.yaml for CIVO
  .github/ISSUE_TEMPLATE/release_checklist.yaml
Labels: kind/chore, area/chore

#2132 Performance of `epinio app list`, tab-completion involving app names
  go.sum
  internal/api/v1/application/match.go
  internal/application/application.go
  internal/application/configurations.go
  internal/application/env.go
  internal/application/ingresses.go
  internal/application/scale.go
  internal/application/services.go
  internal/application/workload.go
Labels: kind/enhancement, area/performance, area/api

#2143 Fixed missing app status
  acceptance/api/v1/application_index_test.go
  internal/api/v1/application/stage.go
  internal/api/v1/configuration/index.go
  internal/application/application.go
  internal/application/application_test.go
  internal/application/applicationfakes/fake_job_lister.go
  internal/application/configurations.go
  internal/application/ingresses.go
  internal/application/workload.go
Labels: kind/bug

#2145 extended logging of log streaming
  helpers/kubernetes/tailer/setup.go
  helpers/kubernetes/tailer/tailer.go
  internal/api/v1/application/logs.go
Labels: kind/enhancement

#2136 Do not wait for service chart deployment by default, new option `--wait`
  docs/references/api/swagger.json
  internal/api/v1/service/create.go
  internal/cli/services.go
  internal/cli/usercmd/service.go
  internal/helm/helm.go
  internal/services/instances.go
  pkg/api/core/v1/models/models.go
Labels: kind/enhancement, area/ux, area/api

#2149 Self-hosted jobs to run on epinio labeled runners only
  .github/workflows/aks-letsencrypt.yml
  .github/workflows/aks.yml
  .github/workflows/clientsync.yml
  .github/workflows/delete_clusters.yml
  .github/workflows/eks-test.yml
  .github/workflows/eks.yml
  .github/workflows/gke-letsencrypt.yml
  .github/workflows/gke-test.yml
  .github/workflows/gke-upgrade.yml
  .github/workflows/gke.yml
  .github/workflows/main.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-sandbox.yml
  .github/workflows/release.yml
  .github/workflows/rke-upgrade.yml
  .github/workflows/rke.yml
  .github/workflows/unpacker-image.yml
  .github/workflows/upgrade.yml
Labels: kind/chore, status/skip-changelog

#2157 Allow missing metrics server
  acceptance/apps_test.go
  internal/application/application.go
  internal/application/workload.go
  internal/cli/usercmd/app.go
  pkg/api/core/v1/models/app.go
Labels: kind/bug, area/ux, area/portability, area/api

#2160 backend side namespace name validation
  acceptance/api/v1/application_create_test.go
  acceptance/api/v1/configurations_test.go
  acceptance/api/v1/namespaces_test.go
  acceptance/apps_test.go
  acceptance/configurations_test.go
  acceptance/namespaces_test.go
  internal/api/v1/application/create.go
  internal/api/v1/configuration/create.go
  internal/api/v1/namespace/create.go
  internal/cli/usercmd/app.go
  internal/cli/usercmd/configuration.go
  internal/cli/usercmd/namespace.go
Labels: kind/bug, area/api
