Repository epinio/epinio, pull requests merged in 2023-11, with the labels that each got.

#2677 [ADR] New Authorization roles
  docs/decisions/20231013-authorization-roles.md
Labels: area/documentation

#2685 trial: tweak goreleaser config to mark rc builds as pre-release.
  .goreleaser.yml
Labels: kind/bug

#2687 Moved `version` and `exportregistries` commands
  internal/cli/cmd/exportregistry.go
  internal/cli/cmd/version.go
  internal/cli/root.go
Labels: kind/chore, status/skip-changelog

#2688 Moved `gitconfig` commands in `cmd` package
  internal/cli/cmd/apps.go
  internal/cli/cmd/args.go
  internal/cli/cmd/flags.go
  internal/cli/cmd/gitconfigs.go
  internal/cli/commons.go
  internal/cli/gitconfigs.go
  internal/cli/root.go
Labels: kind/chore, status/skip-changelog

#2694 Updated Go dependencies, removed deprecated pkgs
  acceptance/api/v1/application_exec_test.go
  acceptance/api/v1/application_export_test.go
  go.mod
  go.sum
  helpers/cahash/cahash.go
  internal/api/v1/application/export.go
  internal/api/v1/application/part.go
  internal/api/v1/application/stage.go
Labels: kind/dependencies

#2689 Added `EpinioArgValidator` for matchers autocomplete
  internal/cli/cmd/apps.go
  internal/cli/cmd/args.go
  internal/cli/cmd/cmdfakes/fake_catalog_matcher.go
  internal/cli/cmd/cmdfakes/fake_configuration_matcher.go
  internal/cli/cmd/cmdfakes/fake_namespace_matcher.go
  internal/cli/cmd/cmdfakes/fake_namespace_service.go
  internal/cli/cmd/configurations.go
  internal/cli/cmd/namespaces.go
  internal/cli/cmd/namespaces_test.go
  internal/cli/cmd/services.go
  internal/cli/cmd/target.go
  internal/cli/usercmd/configuration.go
  internal/cli/usercmd/namespace.go
  internal/cli/usercmd/service.go
Labels: kind/chore, status/skip-changelog

#2698 Fixed missing repo update when chart not found
  internal/helm/helm.go
Labels: kind/bug

#2701 detect users defined multiple times and reject them
  internal/api/v1/middleware/authentication.go
  internal/api/v1/middleware/token.go
  internal/auth/auth.go
  internal/auth/auth_test.go
Labels: kind/bug

#2710 Change service name definition, switch to metadata.name for consistency
  internal/services/catalog.go
Labels: kind/bug

#2719 Added better error handling for panics
  internal/api/v1/middleware/recovery.go
  internal/cli/server/server.go
  pkg/api/core/v1/client/http.go
  pkg/api/core/v1/client/http_test.go
  pkg/api/core/v1/errors/errors.go
Labels: kind/enhancement

#2720 Initialize annotations map for new users
  internal/auth/user.go
Labels: kind/bug, status/skip-changelog

#2721 epinio-binary grown to 100Mi
  scripts/patch-epinio-deployment.sh
Labels: status/devops admin

#2724 Improve the front matter generated.
  internal/cli/docs/generate-cli-docs.go
Labels: area/documentation, safe to test

#2726 Fix problem with Docusaurus generated page.
  internal/cli/docs/generate-cli-docs.go
Labels: area/documentation

#2729 Added `--output json` to info command
  acceptance/info_test.go
  internal/cli/cmd/info.go
  internal/cli/cmd/info_test.go
  internal/cli/root.go
  internal/cli/usercmd/info.go
Labels: kind/enhancement
